// @generated by protoc-gen-es v2.6.3
// @generated from file creatures/v1/creature.proto (package creatures.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file creatures/v1/creature.proto.
 */
export const file_creatures_v1_creature = /*@__PURE__*/
  fileDesc("ChtjcmVhdHVyZXMvdjEvY3JlYXR1cmUucHJvdG8SDGNyZWF0dXJlcy52MSL4AwoIQ3JlYXR1cmUaaAoVQXR0cmlidXRlTW9kaWZpY2F0aW9uEg0KBWRlbHRhGAEgASgFEh8KF25lZ2F0ZV9wb3NpdGl2ZV9lZmZlY3RzGAIgASgIEh8KF25lZ2F0ZV9uZWdhdGl2ZV9lZmZlY3RzGAMgASgIGuMBCgRLaW5kEgoKAmlkGAEgASgJEgwKBHRhZ3MYAiADKAkSOwoObW92ZW1lbnRfdHlwZXMYAyADKA4yIy5jcmVhdHVyZXMudjEuQ3JlYXR1cmUuTW92ZW1lbnRUeXBlEhcKD25hdGl2ZV90ZXJyYWlucxgEIAMoCRprCgZGaWx0ZXISCwoDYWxsGAEgASgIEhMKC2luY2x1ZGVfaWRzGAIgAygJEhMKC2V4Y2x1ZGVfaWRzGAMgAygJEhQKDGluY2x1ZGVfdGFncxgEIAMoCRIUCgxleGNsdWRlX3RhZ3MYBSADKAkimwEKDE1vdmVtZW50VHlwZRIdChlNT1ZFTUVOVF9UWVBFX1VOU1BFQ0lGSUVEEAASGQoVTU9WRU1FTlRfVFlQRV9XQUxLSU5HEAESGgoWTU9WRU1FTlRfVFlQRV9TV0lNTUlORxACEhgKFE1PVkVNRU5UX1RZUEVfRkxZSU5HEAMSGwoXTU9WRU1FTlRfVFlQRV9QT1JUQUxJTkcQBEKnAQoQY29tLmNyZWF0dXJlcy52MUINQ3JlYXR1cmVQcm90b1ABWjNnaXRodWIuY29tL29wZW5oZXhlcy9wcm90by9jcmVhdHVyZXMvdjE7Y3JlYXR1cmVzdjGiAgNDWFiqAgxDcmVhdHVyZXMuVjHKAgxDcmVhdHVyZXNcVjHiAhhDcmVhdHVyZXNcVjFcR1BCTWV0YWRhdGHqAg1DcmVhdHVyZXM6OlYxYgZwcm90bzM");

/**
 * Describes the message creatures.v1.Creature.
 * Use `create(CreatureSchema)` to create a new message.
 */
export const CreatureSchema = /*@__PURE__*/
  messageDesc(file_creatures_v1_creature, 0);

/**
 * Describes the message creatures.v1.Creature.AttributeModification.
 * Use `create(Creature_AttributeModificationSchema)` to create a new message.
 */
export const Creature_AttributeModificationSchema = /*@__PURE__*/
  messageDesc(file_creatures_v1_creature, 0, 0);

/**
 * Describes the message creatures.v1.Creature.Kind.
 * Use `create(Creature_KindSchema)` to create a new message.
 */
export const Creature_KindSchema = /*@__PURE__*/
  messageDesc(file_creatures_v1_creature, 0, 1);

/**
 * Describes the message creatures.v1.Creature.Kind.Filter.
 * Use `create(Creature_Kind_FilterSchema)` to create a new message.
 */
export const Creature_Kind_FilterSchema = /*@__PURE__*/
  messageDesc(file_creatures_v1_creature, 0, 1, 0);

/**
 * Describes the enum creatures.v1.Creature.MovementType.
 */
export const Creature_MovementTypeSchema = /*@__PURE__*/
  enumDesc(file_creatures_v1_creature, 0, 0);

/**
 * @generated from enum creatures.v1.Creature.MovementType
 */
export const Creature_MovementType = /*@__PURE__*/
  tsEnum(Creature_MovementTypeSchema);

