// @generated by protoc-gen-es v2.6.3
// @generated from file game/v1/game.proto (package game.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_progress_v1_progress } from "../../progress/v1/progress_pb";
import { file_world_v1_world } from "../../world/v1/world_pb";

/**
 * Describes the file game/v1/game.proto.
 */
export const file_game_v1_game = /*@__PURE__*/
  fileDesc("ChJnYW1lL3YxL2dhbWUucHJvdG8SB2dhbWUudjEilwEKFUdldFNhbXBsZVdvcmxkUmVxdWVzdBIUCgx0b3RhbF9sYXllcnMYASABKA0SEgoKdG90YWxfcm93cxgCIAEoDRIVCg10b3RhbF9jb2x1bW5zGAMgASgNEhwKFG1heF9yb3dzX3Blcl9zZWdtZW50GAQgASgNEh8KF21heF9jb2x1bW5zX3Blcl9zZWdtZW50GAUgASgNImEKFkdldFNhbXBsZVdvcmxkUmVzcG9uc2USHgoFd29ybGQYASABKAsyDy53b3JsZC52MS5Xb3JsZBInCghwcm9ncmVzcxgCIAEoCzIVLnByb2dyZXNzLnYxLlByb2dyZXNzMmIKC0dhbWVTZXJ2aWNlElMKDkdldFNhbXBsZVdvcmxkEh4uZ2FtZS52MS5HZXRTYW1wbGVXb3JsZFJlcXVlc3QaHy5nYW1lLnYxLkdldFNhbXBsZVdvcmxkUmVzcG9uc2UwAUKAAQoLY29tLmdhbWUudjFCCUdhbWVQcm90b1ABWilnaXRodWIuY29tL29wZW5oZXhlcy9wcm90by9nYW1lL3YxO2dhbWV2MaICA0dYWKoCB0dhbWUuVjHKAgdHYW1lXFYx4gITR2FtZVxWMVxHUEJNZXRhZGF0YeoCCEdhbWU6OlYxYgZwcm90bzM", [file_progress_v1_progress, file_world_v1_world]);

/**
 * Describes the message game.v1.GetSampleWorldRequest.
 * Use `create(GetSampleWorldRequestSchema)` to create a new message.
 */
export const GetSampleWorldRequestSchema = /*@__PURE__*/
  messageDesc(file_game_v1_game, 0);

/**
 * Describes the message game.v1.GetSampleWorldResponse.
 * Use `create(GetSampleWorldResponseSchema)` to create a new message.
 */
export const GetSampleWorldResponseSchema = /*@__PURE__*/
  messageDesc(file_game_v1_game, 1);

/**
 * @generated from service game.v1.GameService
 */
export const GameService = /*@__PURE__*/
  serviceDesc(file_game_v1_game, 0);

