// @generated by protoc-gen-es v2.6.3
// @generated from file game/v1/game.proto (package game.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { World } from "../../world/v1/world_pb";
import type { Progress } from "../../progress/v1/progress_pb";

/**
 * Describes the file game/v1/game.proto.
 */
export declare const file_game_v1_game: GenFile;

/**
 * @generated from message game.v1.GetSampleWorldRequest
 */
export declare type GetSampleWorldRequest = Message<"game.v1.GetSampleWorldRequest"> & {
  /**
   * @generated from field: uint32 total_rows = 1;
   */
  totalRows: number;

  /**
   * @generated from field: uint32 total_columns = 2;
   */
  totalColumns: number;

  /**
   * @generated from field: uint32 max_rows_per_segment = 3;
   */
  maxRowsPerSegment: number;

  /**
   * @generated from field: uint32 max_columns_per_segment = 4;
   */
  maxColumnsPerSegment: number;
};

/**
 * Describes the message game.v1.GetSampleWorldRequest.
 * Use `create(GetSampleWorldRequestSchema)` to create a new message.
 */
export declare const GetSampleWorldRequestSchema: GenMessage<GetSampleWorldRequest>;

/**
 * @generated from message game.v1.GetSampleWorldResponse
 */
export declare type GetSampleWorldResponse = Message<"game.v1.GetSampleWorldResponse"> & {
  /**
   * partial
   *
   * @generated from field: world.v1.World world = 1;
   */
  world?: World;

  /**
   * @generated from field: progress.v1.Progress progress = 2;
   */
  progress?: Progress;
};

/**
 * Describes the message game.v1.GetSampleWorldResponse.
 * Use `create(GetSampleWorldResponseSchema)` to create a new message.
 */
export declare const GetSampleWorldResponseSchema: GenMessage<GetSampleWorldResponse>;

/**
 * @generated from service game.v1.GameService
 */
export declare const GameService: GenService<{
  /**
   * @generated from rpc game.v1.GameService.GetSampleWorld
   */
  getSampleWorld: {
    methodKind: "server_streaming";
    input: typeof GetSampleWorldRequestSchema;
    output: typeof GetSampleWorldResponseSchema;
  },
}>;

