// @generated by protoc-gen-es v2.6.3
// @generated from file progress/v1/progress.proto (package progress.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file progress/v1/progress.proto.
 */
export const file_progress_v1_progress = /*@__PURE__*/
  fileDesc("Chpwcm9ncmVzcy92MS9wcm9ncmVzcy5wcm90bxILcHJvZ3Jlc3MudjEi1AEKBVN0YWdlEg0KBXRpdGxlGAEgASgJEhAKCHN1YnRpdGxlGAIgASgJEicKBXN0YXRlGAMgASgOMhgucHJvZ3Jlc3MudjEuU3RhZ2UuU3RhdGUSKwoIZHVyYXRpb24YBCABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb24iVAoFU3RhdGUSFQoRU1RBVEVfVU5TUEVDSUZJRUQQABIRCg1TVEFURV9XQUlUSU5HEAESEQoNU1RBVEVfUlVOTklORxACEg4KClNUQVRFX0RPTkUQAyJCCghQcm9ncmVzcxISCgpwZXJjZW50YWdlGAEgASgBEiIKBnN0YWdlcxgCIAMoCzISLnByb2dyZXNzLnYxLlN0YWdlQqABCg9jb20ucHJvZ3Jlc3MudjFCDVByb2dyZXNzUHJvdG9QAVoxZ2l0aHViLmNvbS9vcGVuaGV4ZXMvcHJvdG8vcHJvZ3Jlc3MvdjE7cHJvZ3Jlc3N2MaICA1BYWKoCC1Byb2dyZXNzLlYxygILUHJvZ3Jlc3NcVjHiAhdQcm9ncmVzc1xWMVxHUEJNZXRhZGF0YeoCDFByb2dyZXNzOjpWMWIGcHJvdG8z", [file_google_protobuf_duration]);

/**
 * Describes the message progress.v1.Stage.
 * Use `create(StageSchema)` to create a new message.
 */
export const StageSchema = /*@__PURE__*/
  messageDesc(file_progress_v1_progress, 0);

/**
 * Describes the enum progress.v1.Stage.State.
 */
export const Stage_StateSchema = /*@__PURE__*/
  enumDesc(file_progress_v1_progress, 0, 0);

/**
 * @generated from enum progress.v1.Stage.State
 */
export const Stage_State = /*@__PURE__*/
  tsEnum(Stage_StateSchema);

/**
 * Describes the message progress.v1.Progress.
 * Use `create(ProgressSchema)` to create a new message.
 */
export const ProgressSchema = /*@__PURE__*/
  messageDesc(file_progress_v1_progress, 1);

