// @generated by protoc-gen-es v2.6.3
// @generated from file progress/v1/progress.proto (package progress.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Duration } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file progress/v1/progress.proto.
 */
export declare const file_progress_v1_progress: GenFile;

/**
 * @generated from message progress.v1.Stage
 */
export declare type Stage = Message<"progress.v1.Stage"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * @generated from field: string subtitle = 2;
   */
  subtitle: string;

  /**
   * @generated from field: progress.v1.Stage.State state = 3;
   */
  state: Stage_State;

  /**
   * @generated from field: google.protobuf.Duration duration = 4;
   */
  duration?: Duration;
};

/**
 * Describes the message progress.v1.Stage.
 * Use `create(StageSchema)` to create a new message.
 */
export declare const StageSchema: GenMessage<Stage>;

/**
 * @generated from enum progress.v1.Stage.State
 */
export enum Stage_State {
  /**
   * @generated from enum value: STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STATE_WAITING = 1;
   */
  WAITING = 1,

  /**
   * @generated from enum value: STATE_RUNNING = 2;
   */
  RUNNING = 2,

  /**
   * @generated from enum value: STATE_DONE = 3;
   */
  DONE = 3,
}

/**
 * Describes the enum progress.v1.Stage.State.
 */
export declare const Stage_StateSchema: GenEnum<Stage_State>;

/**
 * @generated from message progress.v1.Progress
 */
export declare type Progress = Message<"progress.v1.Progress"> & {
  /**
   * @generated from field: double percentage = 1;
   */
  percentage: number;

  /**
   * @generated from field: repeated progress.v1.Stage stages = 2;
   */
  stages: Stage[];
};

/**
 * Describes the message progress.v1.Progress.
 * Use `create(ProgressSchema)` to create a new message.
 */
export declare const ProgressSchema: GenMessage<Progress>;

