// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: game/v1/game.proto

package gamev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/openhexes/proto/game/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GameServiceName is the fully-qualified name of the GameService service.
	GameServiceName = "game.v1.GameService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GameServiceGetSampleWorldProcedure is the fully-qualified name of the GameService's
	// GetSampleWorld RPC.
	GameServiceGetSampleWorldProcedure = "/game.v1.GameService/GetSampleWorld"
)

// GameServiceClient is a client for the game.v1.GameService service.
type GameServiceClient interface {
	GetSampleWorld(context.Context, *connect.Request[v1.GetSampleWorldRequest]) (*connect.ServerStreamForClient[v1.GetSampleWorldResponse], error)
}

// NewGameServiceClient constructs a client for the game.v1.GameService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGameServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GameServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	gameServiceMethods := v1.File_game_v1_game_proto.Services().ByName("GameService").Methods()
	return &gameServiceClient{
		getSampleWorld: connect.NewClient[v1.GetSampleWorldRequest, v1.GetSampleWorldResponse](
			httpClient,
			baseURL+GameServiceGetSampleWorldProcedure,
			connect.WithSchema(gameServiceMethods.ByName("GetSampleWorld")),
			connect.WithClientOptions(opts...),
		),
	}
}

// gameServiceClient implements GameServiceClient.
type gameServiceClient struct {
	getSampleWorld *connect.Client[v1.GetSampleWorldRequest, v1.GetSampleWorldResponse]
}

// GetSampleWorld calls game.v1.GameService.GetSampleWorld.
func (c *gameServiceClient) GetSampleWorld(ctx context.Context, req *connect.Request[v1.GetSampleWorldRequest]) (*connect.ServerStreamForClient[v1.GetSampleWorldResponse], error) {
	return c.getSampleWorld.CallServerStream(ctx, req)
}

// GameServiceHandler is an implementation of the game.v1.GameService service.
type GameServiceHandler interface {
	GetSampleWorld(context.Context, *connect.Request[v1.GetSampleWorldRequest], *connect.ServerStream[v1.GetSampleWorldResponse]) error
}

// NewGameServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGameServiceHandler(svc GameServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	gameServiceMethods := v1.File_game_v1_game_proto.Services().ByName("GameService").Methods()
	gameServiceGetSampleWorldHandler := connect.NewServerStreamHandler(
		GameServiceGetSampleWorldProcedure,
		svc.GetSampleWorld,
		connect.WithSchema(gameServiceMethods.ByName("GetSampleWorld")),
		connect.WithHandlerOptions(opts...),
	)
	return "/game.v1.GameService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GameServiceGetSampleWorldProcedure:
			gameServiceGetSampleWorldHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGameServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGameServiceHandler struct{}

func (UnimplementedGameServiceHandler) GetSampleWorld(context.Context, *connect.Request[v1.GetSampleWorldRequest], *connect.ServerStream[v1.GetSampleWorldResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("game.v1.GameService.GetSampleWorld is not implemented"))
}
