// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: magic/v1/spell.proto

package magicv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Spell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tags          map[string]bool        `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spell) Reset() {
	*x = Spell{}
	mi := &file_magic_v1_spell_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spell) ProtoMessage() {}

func (x *Spell) ProtoReflect() protoreflect.Message {
	mi := &file_magic_v1_spell_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spell.ProtoReflect.Descriptor instead.
func (*Spell) Descriptor() ([]byte, []int) {
	return file_magic_v1_spell_proto_rawDescGZIP(), []int{0}
}

func (x *Spell) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Spell) GetTags() map[string]bool {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Spell_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           bool                   `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	IncludeIds    []string               `protobuf:"bytes,2,rep,name=include_ids,json=includeIds,proto3" json:"include_ids,omitempty"`
	ExcludeIds    []string               `protobuf:"bytes,3,rep,name=exclude_ids,json=excludeIds,proto3" json:"exclude_ids,omitempty"`
	IncludeTags   []string               `protobuf:"bytes,4,rep,name=include_tags,json=includeTags,proto3" json:"include_tags,omitempty"`
	ExcludeTags   []string               `protobuf:"bytes,5,rep,name=exclude_tags,json=excludeTags,proto3" json:"exclude_tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spell_Filter) Reset() {
	*x = Spell_Filter{}
	mi := &file_magic_v1_spell_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spell_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spell_Filter) ProtoMessage() {}

func (x *Spell_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_magic_v1_spell_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spell_Filter.ProtoReflect.Descriptor instead.
func (*Spell_Filter) Descriptor() ([]byte, []int) {
	return file_magic_v1_spell_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Spell_Filter) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *Spell_Filter) GetIncludeIds() []string {
	if x != nil {
		return x.IncludeIds
	}
	return nil
}

func (x *Spell_Filter) GetExcludeIds() []string {
	if x != nil {
		return x.ExcludeIds
	}
	return nil
}

func (x *Spell_Filter) GetIncludeTags() []string {
	if x != nil {
		return x.IncludeTags
	}
	return nil
}

func (x *Spell_Filter) GetExcludeTags() []string {
	if x != nil {
		return x.ExcludeTags
	}
	return nil
}

var File_magic_v1_spell_proto protoreflect.FileDescriptor

const file_magic_v1_spell_proto_rawDesc = "" +
	"\n" +
	"\x14magic/v1/spell.proto\x12\bmagic.v1\"\xa4\x02\n" +
	"\x05Spell\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04tags\x18\x02 \x03(\v2\x19.magic.v1.Spell.TagsEntryR\x04tags\x1a\xa2\x01\n" +
	"\x06Filter\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x1f\n" +
	"\vinclude_ids\x18\x02 \x03(\tR\n" +
	"includeIds\x12\x1f\n" +
	"\vexclude_ids\x18\x03 \x03(\tR\n" +
	"excludeIds\x12!\n" +
	"\finclude_tags\x18\x04 \x03(\tR\vincludeTags\x12!\n" +
	"\fexclude_tags\x18\x05 \x03(\tR\vexcludeTags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01B\x88\x01\n" +
	"\fcom.magic.v1B\n" +
	"SpellProtoP\x01Z+github.com/openhexes/proto/magic/v1;magicv1\xa2\x02\x03MXX\xaa\x02\bMagic.V1\xca\x02\bMagic\\V1\xe2\x02\x14Magic\\V1\\GPBMetadata\xea\x02\tMagic::V1b\x06proto3"

var (
	file_magic_v1_spell_proto_rawDescOnce sync.Once
	file_magic_v1_spell_proto_rawDescData []byte
)

func file_magic_v1_spell_proto_rawDescGZIP() []byte {
	file_magic_v1_spell_proto_rawDescOnce.Do(func() {
		file_magic_v1_spell_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_magic_v1_spell_proto_rawDesc), len(file_magic_v1_spell_proto_rawDesc)))
	})
	return file_magic_v1_spell_proto_rawDescData
}

var file_magic_v1_spell_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_magic_v1_spell_proto_goTypes = []any{
	(*Spell)(nil),        // 0: magic.v1.Spell
	(*Spell_Filter)(nil), // 1: magic.v1.Spell.Filter
	nil,                  // 2: magic.v1.Spell.TagsEntry
}
var file_magic_v1_spell_proto_depIdxs = []int32{
	2, // 0: magic.v1.Spell.tags:type_name -> magic.v1.Spell.TagsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_magic_v1_spell_proto_init() }
func file_magic_v1_spell_proto_init() {
	if File_magic_v1_spell_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_magic_v1_spell_proto_rawDesc), len(file_magic_v1_spell_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_magic_v1_spell_proto_goTypes,
		DependencyIndexes: file_magic_v1_spell_proto_depIdxs,
		MessageInfos:      file_magic_v1_spell_proto_msgTypes,
	}.Build()
	File_magic_v1_spell_proto = out.File
	file_magic_v1_spell_proto_goTypes = nil
	file_magic_v1_spell_proto_depIdxs = nil
}
