// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: world/v1/world.proto

package worldv1

import (
	v12 "github.com/openhexes/proto/creature/v1"
	v11 "github.com/openhexes/proto/magic/v1"
	v1 "github.com/openhexes/proto/map/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type World struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	Layers           []*v1.Grid               `protobuf:"bytes,1,rep,name=layers,proto3" json:"layers,omitempty"`
	TerrainRegistry  map[string]*v1.Terrain   `protobuf:"bytes,2,rep,name=terrain_registry,json=terrainRegistry,proto3" json:"terrain_registry,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SpellRegistry    map[string]*v11.Spell    `protobuf:"bytes,3,rep,name=spell_registry,json=spellRegistry,proto3" json:"spell_registry,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatureRegistry map[string]*v12.Creature `protobuf:"bytes,4,rep,name=creature_registry,json=creatureRegistry,proto3" json:"creature_registry,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *World) Reset() {
	*x = World{}
	mi := &file_world_v1_world_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *World) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*World) ProtoMessage() {}

func (x *World) ProtoReflect() protoreflect.Message {
	mi := &file_world_v1_world_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use World.ProtoReflect.Descriptor instead.
func (*World) Descriptor() ([]byte, []int) {
	return file_world_v1_world_proto_rawDescGZIP(), []int{0}
}

func (x *World) GetLayers() []*v1.Grid {
	if x != nil {
		return x.Layers
	}
	return nil
}

func (x *World) GetTerrainRegistry() map[string]*v1.Terrain {
	if x != nil {
		return x.TerrainRegistry
	}
	return nil
}

func (x *World) GetSpellRegistry() map[string]*v11.Spell {
	if x != nil {
		return x.SpellRegistry
	}
	return nil
}

func (x *World) GetCreatureRegistry() map[string]*v12.Creature {
	if x != nil {
		return x.CreatureRegistry
	}
	return nil
}

var File_world_v1_world_proto protoreflect.FileDescriptor

const file_world_v1_world_proto_rawDesc = "" +
	"\n" +
	"\x14world/v1/world.proto\x12\bworld.v1\x1a\x1acreature/v1/creature.proto\x1a\x14magic/v1/spell.proto\x1a\x14map/v1/terrain.proto\x1a\x11map/v1/tile.proto\"\xa1\x04\n" +
	"\x05World\x12$\n" +
	"\x06layers\x18\x01 \x03(\v2\f.map.v1.GridR\x06layers\x12O\n" +
	"\x10terrain_registry\x18\x02 \x03(\v2$.world.v1.World.TerrainRegistryEntryR\x0fterrainRegistry\x12I\n" +
	"\x0espell_registry\x18\x03 \x03(\v2\".world.v1.World.SpellRegistryEntryR\rspellRegistry\x12R\n" +
	"\x11creature_registry\x18\x04 \x03(\v2%.world.v1.World.CreatureRegistryEntryR\x10creatureRegistry\x1aS\n" +
	"\x14TerrainRegistryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.map.v1.TerrainR\x05value:\x028\x01\x1aQ\n" +
	"\x12SpellRegistryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.magic.v1.SpellR\x05value:\x028\x01\x1aZ\n" +
	"\x15CreatureRegistryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.creature.v1.CreatureR\x05value:\x028\x01B\x88\x01\n" +
	"\fcom.world.v1B\n" +
	"WorldProtoP\x01Z+github.com/openhexes/proto/world/v1;worldv1\xa2\x02\x03WXX\xaa\x02\bWorld.V1\xca\x02\bWorld\\V1\xe2\x02\x14World\\V1\\GPBMetadata\xea\x02\tWorld::V1b\x06proto3"

var (
	file_world_v1_world_proto_rawDescOnce sync.Once
	file_world_v1_world_proto_rawDescData []byte
)

func file_world_v1_world_proto_rawDescGZIP() []byte {
	file_world_v1_world_proto_rawDescOnce.Do(func() {
		file_world_v1_world_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_world_v1_world_proto_rawDesc), len(file_world_v1_world_proto_rawDesc)))
	})
	return file_world_v1_world_proto_rawDescData
}

var file_world_v1_world_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_world_v1_world_proto_goTypes = []any{
	(*World)(nil),        // 0: world.v1.World
	nil,                  // 1: world.v1.World.TerrainRegistryEntry
	nil,                  // 2: world.v1.World.SpellRegistryEntry
	nil,                  // 3: world.v1.World.CreatureRegistryEntry
	(*v1.Grid)(nil),      // 4: map.v1.Grid
	(*v1.Terrain)(nil),   // 5: map.v1.Terrain
	(*v11.Spell)(nil),    // 6: magic.v1.Spell
	(*v12.Creature)(nil), // 7: creature.v1.Creature
}
var file_world_v1_world_proto_depIdxs = []int32{
	4, // 0: world.v1.World.layers:type_name -> map.v1.Grid
	1, // 1: world.v1.World.terrain_registry:type_name -> world.v1.World.TerrainRegistryEntry
	2, // 2: world.v1.World.spell_registry:type_name -> world.v1.World.SpellRegistryEntry
	3, // 3: world.v1.World.creature_registry:type_name -> world.v1.World.CreatureRegistryEntry
	5, // 4: world.v1.World.TerrainRegistryEntry.value:type_name -> map.v1.Terrain
	6, // 5: world.v1.World.SpellRegistryEntry.value:type_name -> magic.v1.Spell
	7, // 6: world.v1.World.CreatureRegistryEntry.value:type_name -> creature.v1.Creature
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_world_v1_world_proto_init() }
func file_world_v1_world_proto_init() {
	if File_world_v1_world_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_world_v1_world_proto_rawDesc), len(file_world_v1_world_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_world_v1_world_proto_goTypes,
		DependencyIndexes: file_world_v1_world_proto_depIdxs,
		MessageInfos:      file_world_v1_world_proto_msgTypes,
	}.Build()
	File_world_v1_world_proto = out.File
	file_world_v1_world_proto_goTypes = nil
	file_world_v1_world_proto_depIdxs = nil
}
