// @generated by protoc-gen-es v2.6.3
// @generated from file iam/v1/iam.proto (package iam.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file iam/v1/iam.proto.
 */
export const file_iam_v1_iam = /*@__PURE__*/
  fileDesc("ChBpYW0vdjEvaWFtLnByb3RvEgZpYW0udjEitwEKB0FjY291bnQSCgoCaWQYASABKAkSIgoEbWV0YRgCIAEoCzIULmlhbS52MS5BY2NvdW50Lk1ldGESDQoFZW1haWwYAyABKAkabQoETWV0YRIOCgZhY3RpdmUYASABKAgSLgoKY3JlYXRlZF9hdBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASFAoMZGlzcGxheV9uYW1lGAMgASgJEg8KB3BpY3R1cmUYBCABKAkiFwoVUmVzb2x2ZUFjY291bnRSZXF1ZXN0IjoKFlJlc29sdmVBY2NvdW50UmVzcG9uc2USIAoHYWNjb3VudBgBIAEoCzIPLmlhbS52MS5BY2NvdW50IhUKE0xpc3RBY2NvdW50c1JlcXVlc3QiOQoUTGlzdEFjY291bnRzUmVzcG9uc2USIQoIYWNjb3VudHMYASADKAsyDy5pYW0udjEuQWNjb3VudDKqAQoKSUFNU2VydmljZRJPCg5SZXNvbHZlQWNjb3VudBIdLmlhbS52MS5SZXNvbHZlQWNjb3VudFJlcXVlc3QaHi5pYW0udjEuUmVzb2x2ZUFjY291bnRSZXNwb25zZRJLCgxMaXN0QWNjb3VudHMSGy5pYW0udjEuTGlzdEFjY291bnRzUmVxdWVzdBocLmlhbS52MS5MaXN0QWNjb3VudHNSZXNwb25zZTABQngKCmNvbS5pYW0udjFCCElhbVByb3RvUAFaJ2dpdGh1Yi5jb20vb3BlbmhleGVzL3Byb3RvL2lhbS92MTtpYW12MaICA0lYWKoCBklhbS5WMcoCBklhbVxWMeICEklhbVxWMVxHUEJNZXRhZGF0YeoCB0lhbTo6VjFiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * Describes the message iam.v1.Account.
 * Use `create(AccountSchema)` to create a new message.
 */
export const AccountSchema = /*@__PURE__*/
  messageDesc(file_iam_v1_iam, 0);

/**
 * Describes the message iam.v1.Account.Meta.
 * Use `create(Account_MetaSchema)` to create a new message.
 */
export const Account_MetaSchema = /*@__PURE__*/
  messageDesc(file_iam_v1_iam, 0, 0);

/**
 * Describes the message iam.v1.ResolveAccountRequest.
 * Use `create(ResolveAccountRequestSchema)` to create a new message.
 */
export const ResolveAccountRequestSchema = /*@__PURE__*/
  messageDesc(file_iam_v1_iam, 1);

/**
 * Describes the message iam.v1.ResolveAccountResponse.
 * Use `create(ResolveAccountResponseSchema)` to create a new message.
 */
export const ResolveAccountResponseSchema = /*@__PURE__*/
  messageDesc(file_iam_v1_iam, 2);

/**
 * Describes the message iam.v1.ListAccountsRequest.
 * Use `create(ListAccountsRequestSchema)` to create a new message.
 */
export const ListAccountsRequestSchema = /*@__PURE__*/
  messageDesc(file_iam_v1_iam, 3);

/**
 * Describes the message iam.v1.ListAccountsResponse.
 * Use `create(ListAccountsResponseSchema)` to create a new message.
 */
export const ListAccountsResponseSchema = /*@__PURE__*/
  messageDesc(file_iam_v1_iam, 4);

/**
 * @generated from service iam.v1.IAMService
 */
export const IAMService = /*@__PURE__*/
  serviceDesc(file_iam_v1_iam, 0);

