// @generated by protoc-gen-es v2.6.3
// @generated from file iam/v1/iam.proto (package iam.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file iam/v1/iam.proto.
 */
export const file_iam_v1_iam = /*@__PURE__*/
  fileDesc("ChBpYW0vdjEvaWFtLnByb3RvEgZpYW0udjEixgEKB0FjY291bnQSCgoCaWQYASABKAkSIgoEbWV0YRgCIAEoCzIULmlhbS52MS5BY2NvdW50Lk1ldGESDQoFZW1haWwYAyABKAkSDQoFcm9sZXMYBCADKAkabQoETWV0YRIOCgZhY3RpdmUYASABKAgSLgoKY3JlYXRlZF9hdBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASFAoMZGlzcGxheV9uYW1lGAMgASgJEg8KB3BpY3R1cmUYBCABKAkiFwoVUmVzb2x2ZUFjY291bnRSZXF1ZXN0IjoKFlJlc29sdmVBY2NvdW50UmVzcG9uc2USIAoHYWNjb3VudBgBIAEoCzIPLmlhbS52MS5BY2NvdW50IjUKE0xpc3RBY2NvdW50c1JlcXVlc3QSEwoGYWN0aXZlGAEgASgISACIAQFCCQoHX2FjdGl2ZSI5ChRMaXN0QWNjb3VudHNSZXNwb25zZRIhCghhY2NvdW50cxgBIAMoCzIPLmlhbS52MS5BY2NvdW50IjMKEUdldEFjY291bnRSZXF1ZXN0EgoKAmlkGAEgASgJEhIKCndpdGhfcm9sZXMYAiABKAgiNgoSR2V0QWNjb3VudFJlc3BvbnNlEiAKB2FjY291bnQYASABKAsyDy5pYW0udjEuQWNjb3VudCKtAQoeVXBkYXRlQWNjb3VudEFjdGl2YXRpb25SZXF1ZXN0ElQKEGlkX3RvX2FjdGl2YXRpb24YASADKAsyOi5pYW0udjEuVXBkYXRlQWNjb3VudEFjdGl2YXRpb25SZXF1ZXN0LklkVG9BY3RpdmF0aW9uRW50cnkaNQoTSWRUb0FjdGl2YXRpb25FbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAg6AjgBIiEKH1VwZGF0ZUFjY291bnRBY3RpdmF0aW9uUmVzcG9uc2Uy2wIKCklBTVNlcnZpY2USTwoOUmVzb2x2ZUFjY291bnQSHS5pYW0udjEuUmVzb2x2ZUFjY291bnRSZXF1ZXN0Gh4uaWFtLnYxLlJlc29sdmVBY2NvdW50UmVzcG9uc2USSwoMTGlzdEFjY291bnRzEhsuaWFtLnYxLkxpc3RBY2NvdW50c1JlcXVlc3QaHC5pYW0udjEuTGlzdEFjY291bnRzUmVzcG9uc2UwARJDCgpHZXRBY2NvdW50EhkuaWFtLnYxLkdldEFjY291bnRSZXF1ZXN0GhouaWFtLnYxLkdldEFjY291bnRSZXNwb25zZRJqChdVcGRhdGVBY2NvdW50QWN0aXZhdGlvbhImLmlhbS52MS5VcGRhdGVBY2NvdW50QWN0aXZhdGlvblJlcXVlc3QaJy5pYW0udjEuVXBkYXRlQWNjb3VudEFjdGl2YXRpb25SZXNwb25zZUJ4Cgpjb20uaWFtLnYxQghJYW1Qcm90b1ABWidnaXRodWIuY29tL29wZW5oZXhlcy9wcm90by9pYW0vdjE7aWFtdjGiAgNJWFiqAgZJYW0uVjHKAgZJYW1cVjHiAhJJYW1cVjFcR1BCTWV0YWRhdGHqAgdJYW06OlYxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * Describes the message iam.v1.Account.
 * Use `create(AccountSchema)` to create a new message.
 */
export const AccountSchema = /*@__PURE__*/
  messageDesc(file_iam_v1_iam, 0);

/**
 * Describes the message iam.v1.Account.Meta.
 * Use `create(Account_MetaSchema)` to create a new message.
 */
export const Account_MetaSchema = /*@__PURE__*/
  messageDesc(file_iam_v1_iam, 0, 0);

/**
 * Describes the message iam.v1.ResolveAccountRequest.
 * Use `create(ResolveAccountRequestSchema)` to create a new message.
 */
export const ResolveAccountRequestSchema = /*@__PURE__*/
  messageDesc(file_iam_v1_iam, 1);

/**
 * Describes the message iam.v1.ResolveAccountResponse.
 * Use `create(ResolveAccountResponseSchema)` to create a new message.
 */
export const ResolveAccountResponseSchema = /*@__PURE__*/
  messageDesc(file_iam_v1_iam, 2);

/**
 * Describes the message iam.v1.ListAccountsRequest.
 * Use `create(ListAccountsRequestSchema)` to create a new message.
 */
export const ListAccountsRequestSchema = /*@__PURE__*/
  messageDesc(file_iam_v1_iam, 3);

/**
 * Describes the message iam.v1.ListAccountsResponse.
 * Use `create(ListAccountsResponseSchema)` to create a new message.
 */
export const ListAccountsResponseSchema = /*@__PURE__*/
  messageDesc(file_iam_v1_iam, 4);

/**
 * Describes the message iam.v1.GetAccountRequest.
 * Use `create(GetAccountRequestSchema)` to create a new message.
 */
export const GetAccountRequestSchema = /*@__PURE__*/
  messageDesc(file_iam_v1_iam, 5);

/**
 * Describes the message iam.v1.GetAccountResponse.
 * Use `create(GetAccountResponseSchema)` to create a new message.
 */
export const GetAccountResponseSchema = /*@__PURE__*/
  messageDesc(file_iam_v1_iam, 6);

/**
 * Describes the message iam.v1.UpdateAccountActivationRequest.
 * Use `create(UpdateAccountActivationRequestSchema)` to create a new message.
 */
export const UpdateAccountActivationRequestSchema = /*@__PURE__*/
  messageDesc(file_iam_v1_iam, 7);

/**
 * Describes the message iam.v1.UpdateAccountActivationResponse.
 * Use `create(UpdateAccountActivationResponseSchema)` to create a new message.
 */
export const UpdateAccountActivationResponseSchema = /*@__PURE__*/
  messageDesc(file_iam_v1_iam, 8);

/**
 * @generated from service iam.v1.IAMService
 */
export const IAMService = /*@__PURE__*/
  serviceDesc(file_iam_v1_iam, 0);

