// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: iam/v1/iam.proto

package iamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta          *Account_Meta          `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_iam_v1_iam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetMeta() *Account_Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ResolveAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAccountRequest) Reset() {
	*x = ResolveAccountRequest{}
	mi := &file_iam_v1_iam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAccountRequest) ProtoMessage() {}

func (x *ResolveAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAccountRequest.ProtoReflect.Descriptor instead.
func (*ResolveAccountRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{1}
}

type ResolveAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAccountResponse) Reset() {
	*x = ResolveAccountResponse{}
	mi := &file_iam_v1_iam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAccountResponse) ProtoMessage() {}

func (x *ResolveAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAccountResponse.ProtoReflect.Descriptor instead.
func (*ResolveAccountResponse) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type ListAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsRequest) Reset() {
	*x = ListAccountsRequest{}
	mi := &file_iam_v1_iam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRequest) ProtoMessage() {}

func (x *ListAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{3}
}

type ListAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsResponse) Reset() {
	*x = ListAccountsResponse{}
	mi := &file_iam_v1_iam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsResponse) ProtoMessage() {}

func (x *ListAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{4}
}

func (x *ListAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type UpdateAccountActivationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdToActivation map[string]bool        `protobuf:"bytes,1,rep,name=id_to_activation,json=idToActivation,proto3" json:"id_to_activation,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateAccountActivationRequest) Reset() {
	*x = UpdateAccountActivationRequest{}
	mi := &file_iam_v1_iam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountActivationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountActivationRequest) ProtoMessage() {}

func (x *UpdateAccountActivationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountActivationRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountActivationRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAccountActivationRequest) GetIdToActivation() map[string]bool {
	if x != nil {
		return x.IdToActivation
	}
	return nil
}

type UpdateAccountActivationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountActivationResponse) Reset() {
	*x = UpdateAccountActivationResponse{}
	mi := &file_iam_v1_iam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountActivationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountActivationResponse) ProtoMessage() {}

func (x *UpdateAccountActivationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountActivationResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccountActivationResponse) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{6}
}

type Account_Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Picture       string                 `protobuf:"bytes,4,opt,name=picture,proto3" json:"picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account_Meta) Reset() {
	*x = Account_Meta{}
	mi := &file_iam_v1_iam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account_Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account_Meta) ProtoMessage() {}

func (x *Account_Meta) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account_Meta.ProtoReflect.Descriptor instead.
func (*Account_Meta) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Account_Meta) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Account_Meta) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account_Meta) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Account_Meta) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

var File_iam_v1_iam_proto protoreflect.FileDescriptor

const file_iam_v1_iam_proto_rawDesc = "" +
	"\n" +
	"\x10iam/v1/iam.proto\x12\x06iam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf2\x01\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x04meta\x18\x02 \x01(\v2\x14.iam.v1.Account.MetaR\x04meta\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x1a\x96\x01\n" +
	"\x04Meta\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x18\n" +
	"\apicture\x18\x04 \x01(\tR\apicture\"\x17\n" +
	"\x15ResolveAccountRequest\"C\n" +
	"\x16ResolveAccountResponse\x12)\n" +
	"\aaccount\x18\x01 \x01(\v2\x0f.iam.v1.AccountR\aaccount\"\x15\n" +
	"\x13ListAccountsRequest\"C\n" +
	"\x14ListAccountsResponse\x12+\n" +
	"\baccounts\x18\x01 \x03(\v2\x0f.iam.v1.AccountR\baccounts\"\xc9\x01\n" +
	"\x1eUpdateAccountActivationRequest\x12d\n" +
	"\x10id_to_activation\x18\x01 \x03(\v2:.iam.v1.UpdateAccountActivationRequest.IdToActivationEntryR\x0eidToActivation\x1aA\n" +
	"\x13IdToActivationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"!\n" +
	"\x1fUpdateAccountActivationResponse2\x96\x02\n" +
	"\n" +
	"IAMService\x12O\n" +
	"\x0eResolveAccount\x12\x1d.iam.v1.ResolveAccountRequest\x1a\x1e.iam.v1.ResolveAccountResponse\x12K\n" +
	"\fListAccounts\x12\x1b.iam.v1.ListAccountsRequest\x1a\x1c.iam.v1.ListAccountsResponse0\x01\x12j\n" +
	"\x17UpdateAccountActivation\x12&.iam.v1.UpdateAccountActivationRequest\x1a'.iam.v1.UpdateAccountActivationResponseBx\n" +
	"\n" +
	"com.iam.v1B\bIamProtoP\x01Z'github.com/openhexes/proto/iam/v1;iamv1\xa2\x02\x03IXX\xaa\x02\x06Iam.V1\xca\x02\x06Iam\\V1\xe2\x02\x12Iam\\V1\\GPBMetadata\xea\x02\aIam::V1b\x06proto3"

var (
	file_iam_v1_iam_proto_rawDescOnce sync.Once
	file_iam_v1_iam_proto_rawDescData []byte
)

func file_iam_v1_iam_proto_rawDescGZIP() []byte {
	file_iam_v1_iam_proto_rawDescOnce.Do(func() {
		file_iam_v1_iam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iam_v1_iam_proto_rawDesc), len(file_iam_v1_iam_proto_rawDesc)))
	})
	return file_iam_v1_iam_proto_rawDescData
}

var file_iam_v1_iam_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_iam_v1_iam_proto_goTypes = []any{
	(*Account)(nil),                         // 0: iam.v1.Account
	(*ResolveAccountRequest)(nil),           // 1: iam.v1.ResolveAccountRequest
	(*ResolveAccountResponse)(nil),          // 2: iam.v1.ResolveAccountResponse
	(*ListAccountsRequest)(nil),             // 3: iam.v1.ListAccountsRequest
	(*ListAccountsResponse)(nil),            // 4: iam.v1.ListAccountsResponse
	(*UpdateAccountActivationRequest)(nil),  // 5: iam.v1.UpdateAccountActivationRequest
	(*UpdateAccountActivationResponse)(nil), // 6: iam.v1.UpdateAccountActivationResponse
	(*Account_Meta)(nil),                    // 7: iam.v1.Account.Meta
	nil,                                     // 8: iam.v1.UpdateAccountActivationRequest.IdToActivationEntry
	(*timestamppb.Timestamp)(nil),           // 9: google.protobuf.Timestamp
}
var file_iam_v1_iam_proto_depIdxs = []int32{
	7, // 0: iam.v1.Account.meta:type_name -> iam.v1.Account.Meta
	0, // 1: iam.v1.ResolveAccountResponse.account:type_name -> iam.v1.Account
	0, // 2: iam.v1.ListAccountsResponse.accounts:type_name -> iam.v1.Account
	8, // 3: iam.v1.UpdateAccountActivationRequest.id_to_activation:type_name -> iam.v1.UpdateAccountActivationRequest.IdToActivationEntry
	9, // 4: iam.v1.Account.Meta.created_at:type_name -> google.protobuf.Timestamp
	1, // 5: iam.v1.IAMService.ResolveAccount:input_type -> iam.v1.ResolveAccountRequest
	3, // 6: iam.v1.IAMService.ListAccounts:input_type -> iam.v1.ListAccountsRequest
	5, // 7: iam.v1.IAMService.UpdateAccountActivation:input_type -> iam.v1.UpdateAccountActivationRequest
	2, // 8: iam.v1.IAMService.ResolveAccount:output_type -> iam.v1.ResolveAccountResponse
	4, // 9: iam.v1.IAMService.ListAccounts:output_type -> iam.v1.ListAccountsResponse
	6, // 10: iam.v1.IAMService.UpdateAccountActivation:output_type -> iam.v1.UpdateAccountActivationResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_iam_v1_iam_proto_init() }
func file_iam_v1_iam_proto_init() {
	if File_iam_v1_iam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iam_v1_iam_proto_rawDesc), len(file_iam_v1_iam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iam_v1_iam_proto_goTypes,
		DependencyIndexes: file_iam_v1_iam_proto_depIdxs,
		MessageInfos:      file_iam_v1_iam_proto_msgTypes,
	}.Build()
	File_iam_v1_iam_proto = out.File
	file_iam_v1_iam_proto_goTypes = nil
	file_iam_v1_iam_proto_depIdxs = nil
}
