// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID          uuid.UUID
	Active      bool
	CreatedAt   pgtype.Timestamptz
	Email       string
	DisplayName string
	Picture     string
}

type Role struct {
	ID string
}

type RoleBinding struct {
	AccountID uuid.UUID
	RoleID    string
}
