// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: creature/v1/creature.proto

package creaturev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Creature_MovementType int32

const (
	Creature_MOVEMENT_TYPE_UNSPECIFIED Creature_MovementType = 0
	Creature_MOVEMENT_TYPE_WALKING     Creature_MovementType = 1
	Creature_MOVEMENT_TYPE_SWIMMING    Creature_MovementType = 2
	Creature_MOVEMENT_TYPE_FLYING      Creature_MovementType = 3
	Creature_MOVEMENT_TYPE_PORTALING   Creature_MovementType = 4
)

// Enum value maps for Creature_MovementType.
var (
	Creature_MovementType_name = map[int32]string{
		0: "MOVEMENT_TYPE_UNSPECIFIED",
		1: "MOVEMENT_TYPE_WALKING",
		2: "MOVEMENT_TYPE_SWIMMING",
		3: "MOVEMENT_TYPE_FLYING",
		4: "MOVEMENT_TYPE_PORTALING",
	}
	Creature_MovementType_value = map[string]int32{
		"MOVEMENT_TYPE_UNSPECIFIED": 0,
		"MOVEMENT_TYPE_WALKING":     1,
		"MOVEMENT_TYPE_SWIMMING":    2,
		"MOVEMENT_TYPE_FLYING":      3,
		"MOVEMENT_TYPE_PORTALING":   4,
	}
)

func (x Creature_MovementType) Enum() *Creature_MovementType {
	p := new(Creature_MovementType)
	*p = x
	return p
}

func (x Creature_MovementType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Creature_MovementType) Descriptor() protoreflect.EnumDescriptor {
	return file_creature_v1_creature_proto_enumTypes[0].Descriptor()
}

func (Creature_MovementType) Type() protoreflect.EnumType {
	return &file_creature_v1_creature_proto_enumTypes[0]
}

func (x Creature_MovementType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Creature_MovementType.Descriptor instead.
func (Creature_MovementType) EnumDescriptor() ([]byte, []int) {
	return file_creature_v1_creature_proto_rawDescGZIP(), []int{0, 0}
}

type Creature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Creature) Reset() {
	*x = Creature{}
	mi := &file_creature_v1_creature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Creature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Creature) ProtoMessage() {}

func (x *Creature) ProtoReflect() protoreflect.Message {
	mi := &file_creature_v1_creature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Creature.ProtoReflect.Descriptor instead.
func (*Creature) Descriptor() ([]byte, []int) {
	return file_creature_v1_creature_proto_rawDescGZIP(), []int{0}
}

type Creature_AttributeModification struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Delta                 int32                  `protobuf:"varint,1,opt,name=delta,proto3" json:"delta,omitempty"`
	NegatePositiveEffects bool                   `protobuf:"varint,2,opt,name=negate_positive_effects,json=negatePositiveEffects,proto3" json:"negate_positive_effects,omitempty"`
	NegateNegativeEffects bool                   `protobuf:"varint,3,opt,name=negate_negative_effects,json=negateNegativeEffects,proto3" json:"negate_negative_effects,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Creature_AttributeModification) Reset() {
	*x = Creature_AttributeModification{}
	mi := &file_creature_v1_creature_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Creature_AttributeModification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Creature_AttributeModification) ProtoMessage() {}

func (x *Creature_AttributeModification) ProtoReflect() protoreflect.Message {
	mi := &file_creature_v1_creature_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Creature_AttributeModification.ProtoReflect.Descriptor instead.
func (*Creature_AttributeModification) Descriptor() ([]byte, []int) {
	return file_creature_v1_creature_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Creature_AttributeModification) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *Creature_AttributeModification) GetNegatePositiveEffects() bool {
	if x != nil {
		return x.NegatePositiveEffects
	}
	return false
}

func (x *Creature_AttributeModification) GetNegateNegativeEffects() bool {
	if x != nil {
		return x.NegateNegativeEffects
	}
	return false
}

type Creature_Kind struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Id             string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tags           map[string]bool         `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	MovementTypes  []Creature_MovementType `protobuf:"varint,3,rep,packed,name=movement_types,json=movementTypes,proto3,enum=creature.v1.Creature_MovementType" json:"movement_types,omitempty"`
	NativeTerrains []string                `protobuf:"bytes,4,rep,name=native_terrains,json=nativeTerrains,proto3" json:"native_terrains,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Creature_Kind) Reset() {
	*x = Creature_Kind{}
	mi := &file_creature_v1_creature_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Creature_Kind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Creature_Kind) ProtoMessage() {}

func (x *Creature_Kind) ProtoReflect() protoreflect.Message {
	mi := &file_creature_v1_creature_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Creature_Kind.ProtoReflect.Descriptor instead.
func (*Creature_Kind) Descriptor() ([]byte, []int) {
	return file_creature_v1_creature_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Creature_Kind) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Creature_Kind) GetTags() map[string]bool {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Creature_Kind) GetMovementTypes() []Creature_MovementType {
	if x != nil {
		return x.MovementTypes
	}
	return nil
}

func (x *Creature_Kind) GetNativeTerrains() []string {
	if x != nil {
		return x.NativeTerrains
	}
	return nil
}

type Creature_Kind_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           bool                   `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	IncludeIds    []string               `protobuf:"bytes,2,rep,name=include_ids,json=includeIds,proto3" json:"include_ids,omitempty"`
	ExcludeIds    []string               `protobuf:"bytes,3,rep,name=exclude_ids,json=excludeIds,proto3" json:"exclude_ids,omitempty"`
	IncludeTags   []string               `protobuf:"bytes,4,rep,name=include_tags,json=includeTags,proto3" json:"include_tags,omitempty"`
	ExcludeTags   []string               `protobuf:"bytes,5,rep,name=exclude_tags,json=excludeTags,proto3" json:"exclude_tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Creature_Kind_Filter) Reset() {
	*x = Creature_Kind_Filter{}
	mi := &file_creature_v1_creature_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Creature_Kind_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Creature_Kind_Filter) ProtoMessage() {}

func (x *Creature_Kind_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_creature_v1_creature_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Creature_Kind_Filter.ProtoReflect.Descriptor instead.
func (*Creature_Kind_Filter) Descriptor() ([]byte, []int) {
	return file_creature_v1_creature_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *Creature_Kind_Filter) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *Creature_Kind_Filter) GetIncludeIds() []string {
	if x != nil {
		return x.IncludeIds
	}
	return nil
}

func (x *Creature_Kind_Filter) GetExcludeIds() []string {
	if x != nil {
		return x.ExcludeIds
	}
	return nil
}

func (x *Creature_Kind_Filter) GetIncludeTags() []string {
	if x != nil {
		return x.IncludeTags
	}
	return nil
}

func (x *Creature_Kind_Filter) GetExcludeTags() []string {
	if x != nil {
		return x.ExcludeTags
	}
	return nil
}

var File_creature_v1_creature_proto protoreflect.FileDescriptor

const file_creature_v1_creature_proto_rawDesc = "" +
	"\n" +
	"\x1acreature/v1/creature.proto\x12\vcreature.v1\"\xed\x05\n" +
	"\bCreature\x1a\x9d\x01\n" +
	"\x15AttributeModification\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\x05R\x05delta\x126\n" +
	"\x17negate_positive_effects\x18\x02 \x01(\bR\x15negatePositiveEffects\x126\n" +
	"\x17negate_negative_effects\x18\x03 \x01(\bR\x15negateNegativeEffects\x1a\xa2\x03\n" +
	"\x04Kind\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\x04tags\x18\x02 \x03(\v2$.creature.v1.Creature.Kind.TagsEntryR\x04tags\x12I\n" +
	"\x0emovement_types\x18\x03 \x03(\x0e2\".creature.v1.Creature.MovementTypeR\rmovementTypes\x12'\n" +
	"\x0fnative_terrains\x18\x04 \x03(\tR\x0enativeTerrains\x1a\xa2\x01\n" +
	"\x06Filter\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x1f\n" +
	"\vinclude_ids\x18\x02 \x03(\tR\n" +
	"includeIds\x12\x1f\n" +
	"\vexclude_ids\x18\x03 \x03(\tR\n" +
	"excludeIds\x12!\n" +
	"\finclude_tags\x18\x04 \x03(\tR\vincludeTags\x12!\n" +
	"\fexclude_tags\x18\x05 \x03(\tR\vexcludeTags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\x9b\x01\n" +
	"\fMovementType\x12\x1d\n" +
	"\x19MOVEMENT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15MOVEMENT_TYPE_WALKING\x10\x01\x12\x1a\n" +
	"\x16MOVEMENT_TYPE_SWIMMING\x10\x02\x12\x18\n" +
	"\x14MOVEMENT_TYPE_FLYING\x10\x03\x12\x1b\n" +
	"\x17MOVEMENT_TYPE_PORTALING\x10\x04B\xa0\x01\n" +
	"\x0fcom.creature.v1B\rCreatureProtoP\x01Z1github.com/openhexes/proto/creature/v1;creaturev1\xa2\x02\x03CXX\xaa\x02\vCreature.V1\xca\x02\vCreature\\V1\xe2\x02\x17Creature\\V1\\GPBMetadata\xea\x02\fCreature::V1b\x06proto3"

var (
	file_creature_v1_creature_proto_rawDescOnce sync.Once
	file_creature_v1_creature_proto_rawDescData []byte
)

func file_creature_v1_creature_proto_rawDescGZIP() []byte {
	file_creature_v1_creature_proto_rawDescOnce.Do(func() {
		file_creature_v1_creature_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_creature_v1_creature_proto_rawDesc), len(file_creature_v1_creature_proto_rawDesc)))
	})
	return file_creature_v1_creature_proto_rawDescData
}

var file_creature_v1_creature_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_creature_v1_creature_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_creature_v1_creature_proto_goTypes = []any{
	(Creature_MovementType)(0),             // 0: creature.v1.Creature.MovementType
	(*Creature)(nil),                       // 1: creature.v1.Creature
	(*Creature_AttributeModification)(nil), // 2: creature.v1.Creature.AttributeModification
	(*Creature_Kind)(nil),                  // 3: creature.v1.Creature.Kind
	(*Creature_Kind_Filter)(nil),           // 4: creature.v1.Creature.Kind.Filter
	nil,                                    // 5: creature.v1.Creature.Kind.TagsEntry
}
var file_creature_v1_creature_proto_depIdxs = []int32{
	5, // 0: creature.v1.Creature.Kind.tags:type_name -> creature.v1.Creature.Kind.TagsEntry
	0, // 1: creature.v1.Creature.Kind.movement_types:type_name -> creature.v1.Creature.MovementType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_creature_v1_creature_proto_init() }
func file_creature_v1_creature_proto_init() {
	if File_creature_v1_creature_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_creature_v1_creature_proto_rawDesc), len(file_creature_v1_creature_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_creature_v1_creature_proto_goTypes,
		DependencyIndexes: file_creature_v1_creature_proto_depIdxs,
		EnumInfos:         file_creature_v1_creature_proto_enumTypes,
		MessageInfos:      file_creature_v1_creature_proto_msgTypes,
	}.Build()
	File_creature_v1_creature_proto = out.File
	file_creature_v1_creature_proto_goTypes = nil
	file_creature_v1_creature_proto_depIdxs = nil
}
