// @generated by protoc-gen-es v2.6.3
// @generated from file magic/v1/spell.proto (package magic.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file magic/v1/spell.proto.
 */
export const file_magic_v1_spell = /*@__PURE__*/
  fileDesc("ChRtYWdpYy92MS9zcGVsbC5wcm90bxIIbWFnaWMudjEi1gEKBVNwZWxsEgoKAmlkGAEgASgJEicKBHRhZ3MYAiADKAsyGS5tYWdpYy52MS5TcGVsbC5UYWdzRW50cnkaawoGRmlsdGVyEgsKA2FsbBgBIAEoCBITCgtpbmNsdWRlX2lkcxgCIAMoCRITCgtleGNsdWRlX2lkcxgDIAMoCRIUCgxpbmNsdWRlX3RhZ3MYBCADKAkSFAoMZXhjbHVkZV90YWdzGAUgAygJGisKCVRhZ3NFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAg6AjgBQogBCgxjb20ubWFnaWMudjFCClNwZWxsUHJvdG9QAVorZ2l0aHViLmNvbS9vcGVuaGV4ZXMvcHJvdG8vbWFnaWMvdjE7bWFnaWN2MaICA01YWKoCCE1hZ2ljLlYxygIITWFnaWNcVjHiAhRNYWdpY1xWMVxHUEJNZXRhZGF0YeoCCU1hZ2ljOjpWMWIGcHJvdG8z");

/**
 * Describes the message magic.v1.Spell.
 * Use `create(SpellSchema)` to create a new message.
 */
export const SpellSchema = /*@__PURE__*/
  messageDesc(file_magic_v1_spell, 0);

/**
 * Describes the message magic.v1.Spell.Filter.
 * Use `create(Spell_FilterSchema)` to create a new message.
 */
export const Spell_FilterSchema = /*@__PURE__*/
  messageDesc(file_magic_v1_spell, 0, 0);

