// @generated by protoc-gen-es v2.6.3
// @generated from file magic/v1/spell.proto (package magic.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file magic/v1/spell.proto.
 */
export declare const file_magic_v1_spell: GenFile;

/**
 * @generated from message magic.v1.Spell
 */
export declare type Spell = Message<"magic.v1.Spell"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: repeated string tags = 2;
   */
  tags: string[];
};

/**
 * Describes the message magic.v1.Spell.
 * Use `create(SpellSchema)` to create a new message.
 */
export declare const SpellSchema: GenMessage<Spell>;

/**
 * @generated from message magic.v1.Spell.Filter
 */
export declare type Spell_Filter = Message<"magic.v1.Spell.Filter"> & {
  /**
   * @generated from field: bool all = 1;
   */
  all: boolean;

  /**
   * @generated from field: repeated string include_ids = 2;
   */
  includeIds: string[];

  /**
   * @generated from field: repeated string exclude_ids = 3;
   */
  excludeIds: string[];

  /**
   * @generated from field: repeated string include_tags = 4;
   */
  includeTags: string[];

  /**
   * @generated from field: repeated string exclude_tags = 5;
   */
  excludeTags: string[];
};

/**
 * Describes the message magic.v1.Spell.Filter.
 * Use `create(Spell_FilterSchema)` to create a new message.
 */
export declare const Spell_FilterSchema: GenMessage<Spell_Filter>;

