// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: map/v1/compass.proto

package mapv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_DIRECTION_W           Direction = 1
	Direction_DIRECTION_NW          Direction = 2
	Direction_DIRECTION_NE          Direction = 4
	Direction_DIRECTION_E           Direction = 5
	Direction_DIRECTION_SE          Direction = 6
	Direction_DIRECTION_SW          Direction = 7
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_W",
		2: "DIRECTION_NW",
		4: "DIRECTION_NE",
		5: "DIRECTION_E",
		6: "DIRECTION_SE",
		7: "DIRECTION_SW",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_W":           1,
		"DIRECTION_NW":          2,
		"DIRECTION_NE":          4,
		"DIRECTION_E":           5,
		"DIRECTION_SE":          6,
		"DIRECTION_SW":          7,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_map_v1_compass_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_map_v1_compass_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_map_v1_compass_proto_rawDescGZIP(), []int{0}
}

var File_map_v1_compass_proto protoreflect.FileDescriptor

const file_map_v1_compass_proto_rawDesc = "" +
	"\n" +
	"\x14map/v1/compass.proto\x12\x06map.v1*\x90\x01\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vDIRECTION_W\x10\x01\x12\x10\n" +
	"\fDIRECTION_NW\x10\x02\x12\x10\n" +
	"\fDIRECTION_NE\x10\x04\x12\x0f\n" +
	"\vDIRECTION_E\x10\x05\x12\x10\n" +
	"\fDIRECTION_SE\x10\x06\x12\x10\n" +
	"\fDIRECTION_SW\x10\aB|\n" +
	"\n" +
	"com.map.v1B\fCompassProtoP\x01Z'github.com/openhexes/proto/map/v1;mapv1\xa2\x02\x03MXX\xaa\x02\x06Map.V1\xca\x02\x06Map\\V1\xe2\x02\x12Map\\V1\\GPBMetadata\xea\x02\aMap::V1b\x06proto3"

var (
	file_map_v1_compass_proto_rawDescOnce sync.Once
	file_map_v1_compass_proto_rawDescData []byte
)

func file_map_v1_compass_proto_rawDescGZIP() []byte {
	file_map_v1_compass_proto_rawDescOnce.Do(func() {
		file_map_v1_compass_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_map_v1_compass_proto_rawDesc), len(file_map_v1_compass_proto_rawDesc)))
	})
	return file_map_v1_compass_proto_rawDescData
}

var file_map_v1_compass_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_map_v1_compass_proto_goTypes = []any{
	(Direction)(0), // 0: map.v1.Direction
}
var file_map_v1_compass_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_map_v1_compass_proto_init() }
func file_map_v1_compass_proto_init() {
	if File_map_v1_compass_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_map_v1_compass_proto_rawDesc), len(file_map_v1_compass_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_map_v1_compass_proto_goTypes,
		DependencyIndexes: file_map_v1_compass_proto_depIdxs,
		EnumInfos:         file_map_v1_compass_proto_enumTypes,
	}.Build()
	File_map_v1_compass_proto = out.File
	file_map_v1_compass_proto_goTypes = nil
	file_map_v1_compass_proto_depIdxs = nil
}
