// @generated by protoc-gen-es v2.6.3
// @generated from file world/v1/world.proto (package world.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_creature_v1_creature } from "../../creature/v1/creature_pb";
import { file_magic_v1_spell } from "../../magic/v1/spell_pb";
import { file_map_v1_terrain } from "../../map/v1/terrain_pb";
import { file_map_v1_tile } from "../../map/v1/tile_pb";

/**
 * Describes the file world/v1/world.proto.
 */
export const file_world_v1_world = /*@__PURE__*/
  fileDesc("ChR3b3JsZC92MS93b3JsZC5wcm90bxIId29ybGQudjEitQQKBVdvcmxkEh0KBmxheWVycxgBIAMoCzINLm1hcC52MS5MYXllchI1Cg5yZW5kZXJpbmdfc3BlYxgCIAEoCzIdLndvcmxkLnYxLldvcmxkLlJlbmRlcmluZ1NwZWMSPgoQdGVycmFpbl9yZWdpc3RyeRgDIAMoCzIkLndvcmxkLnYxLldvcmxkLlRlcnJhaW5SZWdpc3RyeUVudHJ5EjoKDnNwZWxsX3JlZ2lzdHJ5GAQgAygLMiIud29ybGQudjEuV29ybGQuU3BlbGxSZWdpc3RyeUVudHJ5EkAKEWNyZWF0dXJlX3JlZ2lzdHJ5GAUgAygLMiUud29ybGQudjEuV29ybGQuQ3JlYXR1cmVSZWdpc3RyeUVudHJ5GjgKDVJlbmRlcmluZ1NwZWMSEwoLdGlsZV9oZWlnaHQYASABKAESEgoKdGlsZV93aWR0aBgCIAEoARpHChRUZXJyYWluUmVnaXN0cnlFbnRyeRILCgNrZXkYASABKAkSHgoFdmFsdWUYAiABKAsyDy5tYXAudjEuVGVycmFpbjoCOAEaRQoSU3BlbGxSZWdpc3RyeUVudHJ5EgsKA2tleRgBIAEoCRIeCgV2YWx1ZRgCIAEoCzIPLm1hZ2ljLnYxLlNwZWxsOgI4ARpOChVDcmVhdHVyZVJlZ2lzdHJ5RW50cnkSCwoDa2V5GAEgASgJEiQKBXZhbHVlGAIgASgLMhUuY3JlYXR1cmUudjEuQ3JlYXR1cmU6AjgBQogBCgxjb20ud29ybGQudjFCCldvcmxkUHJvdG9QAVorZ2l0aHViLmNvbS9vcGVuaGV4ZXMvcHJvdG8vd29ybGQvdjE7d29ybGR2MaICA1dYWKoCCFdvcmxkLlYxygIIV29ybGRcVjHiAhRXb3JsZFxWMVxHUEJNZXRhZGF0YeoCCVdvcmxkOjpWMWIGcHJvdG8z", [file_creature_v1_creature, file_magic_v1_spell, file_map_v1_terrain, file_map_v1_tile]);

/**
 * Describes the message world.v1.World.
 * Use `create(WorldSchema)` to create a new message.
 */
export const WorldSchema = /*@__PURE__*/
  messageDesc(file_world_v1_world, 0);

/**
 * Describes the message world.v1.World.RenderingSpec.
 * Use `create(World_RenderingSpecSchema)` to create a new message.
 */
export const World_RenderingSpecSchema = /*@__PURE__*/
  messageDesc(file_world_v1_world, 0, 0);

