// @generated by protoc-gen-es v2.6.3
// @generated from file world/v1/world.proto (package world.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Grid } from "../../map/v1/tile_pb";
import type { Terrain } from "../../map/v1/terrain_pb";
import type { Spell } from "../../magic/v1/spell_pb";
import type { Creature } from "../../creature/v1/creature_pb";

/**
 * Describes the file world/v1/world.proto.
 */
export declare const file_world_v1_world: GenFile;

/**
 * @generated from message world.v1.World
 */
export declare type World = Message<"world.v1.World"> & {
  /**
   * @generated from field: repeated map.v1.Grid layers = 1;
   */
  layers: Grid[];

  /**
   * @generated from field: world.v1.World.RenderingSpec rendering_spec = 2;
   */
  renderingSpec?: World_RenderingSpec;

  /**
   * @generated from field: map<string, map.v1.Terrain> terrain_registry = 3;
   */
  terrainRegistry: { [key: string]: Terrain };

  /**
   * @generated from field: map<string, magic.v1.Spell> spell_registry = 4;
   */
  spellRegistry: { [key: string]: Spell };

  /**
   * @generated from field: map<string, creature.v1.Creature> creature_registry = 5;
   */
  creatureRegistry: { [key: string]: Creature };
};

/**
 * Describes the message world.v1.World.
 * Use `create(WorldSchema)` to create a new message.
 */
export declare const WorldSchema: GenMessage<World>;

/**
 * @generated from message world.v1.World.RenderingSpec
 */
export declare type World_RenderingSpec = Message<"world.v1.World.RenderingSpec"> & {
  /**
   * Both `tile_height` and `tile_width` are in "world units",
   * they're used to sync client- and server-generated SVGs.
   *
   * @generated from field: double tile_height = 1;
   */
  tileHeight: number;

  /**
   * @generated from field: double tile_width = 2;
   */
  tileWidth: number;
};

/**
 * Describes the message world.v1.World.RenderingSpec.
 * Use `create(World_RenderingSpecSchema)` to create a new message.
 */
export declare const World_RenderingSpecSchema: GenMessage<World_RenderingSpec>;

