// @generated by protoc-gen-es v2.6.3
// @generated from file world/v1/world.proto (package world.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_creature_v1_creature } from "../../creature/v1/creature_pb";
import { file_magic_v1_spell } from "../../magic/v1/spell_pb";
import { file_map_v1_terrain } from "../../map/v1/terrain_pb";
import { file_map_v1_tile } from "../../map/v1/tile_pb";

/**
 * Describes the file world/v1/world.proto.
 */
export const file_world_v1_world = /*@__PURE__*/
  fileDesc("ChR3b3JsZC92MS93b3JsZC5wcm90bxIId29ybGQudjEitAQKBVdvcmxkEhwKBmxheWVycxgBIAMoCzIMLm1hcC52MS5HcmlkEjUKDnJlbmRlcmluZ19zcGVjGAIgASgLMh0ud29ybGQudjEuV29ybGQuUmVuZGVyaW5nU3BlYxI+ChB0ZXJyYWluX3JlZ2lzdHJ5GAMgAygLMiQud29ybGQudjEuV29ybGQuVGVycmFpblJlZ2lzdHJ5RW50cnkSOgoOc3BlbGxfcmVnaXN0cnkYBCADKAsyIi53b3JsZC52MS5Xb3JsZC5TcGVsbFJlZ2lzdHJ5RW50cnkSQAoRY3JlYXR1cmVfcmVnaXN0cnkYBSADKAsyJS53b3JsZC52MS5Xb3JsZC5DcmVhdHVyZVJlZ2lzdHJ5RW50cnkaOAoNUmVuZGVyaW5nU3BlYxITCgt0aWxlX2hlaWdodBgBIAEoARISCgp0aWxlX3dpZHRoGAIgASgBGkcKFFRlcnJhaW5SZWdpc3RyeUVudHJ5EgsKA2tleRgBIAEoCRIeCgV2YWx1ZRgCIAEoCzIPLm1hcC52MS5UZXJyYWluOgI4ARpFChJTcGVsbFJlZ2lzdHJ5RW50cnkSCwoDa2V5GAEgASgJEh4KBXZhbHVlGAIgASgLMg8ubWFnaWMudjEuU3BlbGw6AjgBGk4KFUNyZWF0dXJlUmVnaXN0cnlFbnRyeRILCgNrZXkYASABKAkSJAoFdmFsdWUYAiABKAsyFS5jcmVhdHVyZS52MS5DcmVhdHVyZToCOAFCiAEKDGNvbS53b3JsZC52MUIKV29ybGRQcm90b1ABWitnaXRodWIuY29tL29wZW5oZXhlcy9wcm90by93b3JsZC92MTt3b3JsZHYxogIDV1hYqgIIV29ybGQuVjHKAghXb3JsZFxWMeICFFdvcmxkXFYxXEdQQk1ldGFkYXRh6gIJV29ybGQ6OlYxYgZwcm90bzM", [file_creature_v1_creature, file_magic_v1_spell, file_map_v1_terrain, file_map_v1_tile]);

/**
 * Describes the message world.v1.World.
 * Use `create(WorldSchema)` to create a new message.
 */
export const WorldSchema = /*@__PURE__*/
  messageDesc(file_world_v1_world, 0);

/**
 * Describes the message world.v1.World.RenderingSpec.
 * Use `create(World_RenderingSpecSchema)` to create a new message.
 */
export const World_RenderingSpecSchema = /*@__PURE__*/
  messageDesc(file_world_v1_world, 0, 0);

