// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: progress/v1/progress.proto

package progressv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stage_State int32

const (
	Stage_STATE_UNSPECIFIED Stage_State = 0
	Stage_STATE_WAITING     Stage_State = 1
	Stage_STATE_RUNNING     Stage_State = 2
	Stage_STATE_DONE        Stage_State = 3
)

// Enum value maps for Stage_State.
var (
	Stage_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_WAITING",
		2: "STATE_RUNNING",
		3: "STATE_DONE",
	}
	Stage_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_WAITING":     1,
		"STATE_RUNNING":     2,
		"STATE_DONE":        3,
	}
)

func (x Stage_State) Enum() *Stage_State {
	p := new(Stage_State)
	*p = x
	return p
}

func (x Stage_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stage_State) Descriptor() protoreflect.EnumDescriptor {
	return file_progress_v1_progress_proto_enumTypes[0].Descriptor()
}

func (Stage_State) Type() protoreflect.EnumType {
	return &file_progress_v1_progress_proto_enumTypes[0]
}

func (x Stage_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stage_State.Descriptor instead.
func (Stage_State) EnumDescriptor() ([]byte, []int) {
	return file_progress_v1_progress_proto_rawDescGZIP(), []int{0, 0}
}

type Stage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle      string                 `protobuf:"bytes,2,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	State         Stage_State            `protobuf:"varint,3,opt,name=state,proto3,enum=progress.v1.Stage_State" json:"state,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stage) Reset() {
	*x = Stage{}
	mi := &file_progress_v1_progress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage) ProtoMessage() {}

func (x *Stage) ProtoReflect() protoreflect.Message {
	mi := &file_progress_v1_progress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage.ProtoReflect.Descriptor instead.
func (*Stage) Descriptor() ([]byte, []int) {
	return file_progress_v1_progress_proto_rawDescGZIP(), []int{0}
}

func (x *Stage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Stage) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *Stage) GetState() Stage_State {
	if x != nil {
		return x.State
	}
	return Stage_STATE_UNSPECIFIED
}

func (x *Stage) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percentage    float64                `protobuf:"fixed64,1,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Stages        []*Stage               `protobuf:"bytes,2,rep,name=stages,proto3" json:"stages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_progress_v1_progress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_progress_v1_progress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_progress_v1_progress_proto_rawDescGZIP(), []int{1}
}

func (x *Progress) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *Progress) GetStages() []*Stage {
	if x != nil {
		return x.Stages
	}
	return nil
}

var File_progress_v1_progress_proto protoreflect.FileDescriptor

const file_progress_v1_progress_proto_rawDesc = "" +
	"\n" +
	"\x1aprogress/v1/progress.proto\x12\vprogress.v1\x1a\x1egoogle/protobuf/duration.proto\"\xf6\x01\n" +
	"\x05Stage\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n" +
	"\bsubtitle\x18\x02 \x01(\tR\bsubtitle\x12.\n" +
	"\x05state\x18\x03 \x01(\x0e2\x18.progress.v1.Stage.StateR\x05state\x125\n" +
	"\bduration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bduration\"T\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATE_WAITING\x10\x01\x12\x11\n" +
	"\rSTATE_RUNNING\x10\x02\x12\x0e\n" +
	"\n" +
	"STATE_DONE\x10\x03\"V\n" +
	"\bProgress\x12\x1e\n" +
	"\n" +
	"percentage\x18\x01 \x01(\x01R\n" +
	"percentage\x12*\n" +
	"\x06stages\x18\x02 \x03(\v2\x12.progress.v1.StageR\x06stagesB\xa0\x01\n" +
	"\x0fcom.progress.v1B\rProgressProtoP\x01Z1github.com/openhexes/proto/progress/v1;progressv1\xa2\x02\x03PXX\xaa\x02\vProgress.V1\xca\x02\vProgress\\V1\xe2\x02\x17Progress\\V1\\GPBMetadata\xea\x02\fProgress::V1b\x06proto3"

var (
	file_progress_v1_progress_proto_rawDescOnce sync.Once
	file_progress_v1_progress_proto_rawDescData []byte
)

func file_progress_v1_progress_proto_rawDescGZIP() []byte {
	file_progress_v1_progress_proto_rawDescOnce.Do(func() {
		file_progress_v1_progress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_progress_v1_progress_proto_rawDesc), len(file_progress_v1_progress_proto_rawDesc)))
	})
	return file_progress_v1_progress_proto_rawDescData
}

var file_progress_v1_progress_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_progress_v1_progress_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_progress_v1_progress_proto_goTypes = []any{
	(Stage_State)(0),            // 0: progress.v1.Stage.State
	(*Stage)(nil),               // 1: progress.v1.Stage
	(*Progress)(nil),            // 2: progress.v1.Progress
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
}
var file_progress_v1_progress_proto_depIdxs = []int32{
	0, // 0: progress.v1.Stage.state:type_name -> progress.v1.Stage.State
	3, // 1: progress.v1.Stage.duration:type_name -> google.protobuf.Duration
	1, // 2: progress.v1.Progress.stages:type_name -> progress.v1.Stage
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_progress_v1_progress_proto_init() }
func file_progress_v1_progress_proto_init() {
	if File_progress_v1_progress_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_progress_v1_progress_proto_rawDesc), len(file_progress_v1_progress_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_progress_v1_progress_proto_goTypes,
		DependencyIndexes: file_progress_v1_progress_proto_depIdxs,
		EnumInfos:         file_progress_v1_progress_proto_enumTypes,
		MessageInfos:      file_progress_v1_progress_proto_msgTypes,
	}.Build()
	File_progress_v1_progress_proto = out.File
	file_progress_v1_progress_proto_goTypes = nil
	file_progress_v1_progress_proto_depIdxs = nil
}
