// @generated by protoc-gen-es v2.6.3
// @generated from file creature/v1/creature.proto (package creature.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file creature/v1/creature.proto.
 */
export declare const file_creature_v1_creature: GenFile;

/**
 * @generated from message creature.v1.Creature
 */
export declare type Creature = Message<"creature.v1.Creature"> & {
};

/**
 * Describes the message creature.v1.Creature.
 * Use `create(CreatureSchema)` to create a new message.
 */
export declare const CreatureSchema: GenMessage<Creature>;

/**
 * @generated from message creature.v1.Creature.AttributeModification
 */
export declare type Creature_AttributeModification = Message<"creature.v1.Creature.AttributeModification"> & {
  /**
   * @generated from field: int32 delta = 1;
   */
  delta: number;

  /**
   * @generated from field: bool negate_positive_effects = 2;
   */
  negatePositiveEffects: boolean;

  /**
   * @generated from field: bool negate_negative_effects = 3;
   */
  negateNegativeEffects: boolean;
};

/**
 * Describes the message creature.v1.Creature.AttributeModification.
 * Use `create(Creature_AttributeModificationSchema)` to create a new message.
 */
export declare const Creature_AttributeModificationSchema: GenMessage<Creature_AttributeModification>;

/**
 * @generated from message creature.v1.Creature.Kind
 */
export declare type Creature_Kind = Message<"creature.v1.Creature.Kind"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: map<string, bool> tags = 2;
   */
  tags: { [key: string]: boolean };

  /**
   * @generated from field: repeated creature.v1.Creature.MovementType movement_types = 3;
   */
  movementTypes: Creature_MovementType[];

  /**
   * @generated from field: repeated string native_terrains = 4;
   */
  nativeTerrains: string[];
};

/**
 * Describes the message creature.v1.Creature.Kind.
 * Use `create(Creature_KindSchema)` to create a new message.
 */
export declare const Creature_KindSchema: GenMessage<Creature_Kind>;

/**
 * @generated from message creature.v1.Creature.Kind.Filter
 */
export declare type Creature_Kind_Filter = Message<"creature.v1.Creature.Kind.Filter"> & {
  /**
   * @generated from field: bool all = 1;
   */
  all: boolean;

  /**
   * @generated from field: repeated string include_ids = 2;
   */
  includeIds: string[];

  /**
   * @generated from field: repeated string exclude_ids = 3;
   */
  excludeIds: string[];

  /**
   * @generated from field: repeated string include_tags = 4;
   */
  includeTags: string[];

  /**
   * @generated from field: repeated string exclude_tags = 5;
   */
  excludeTags: string[];
};

/**
 * Describes the message creature.v1.Creature.Kind.Filter.
 * Use `create(Creature_Kind_FilterSchema)` to create a new message.
 */
export declare const Creature_Kind_FilterSchema: GenMessage<Creature_Kind_Filter>;

/**
 * @generated from enum creature.v1.Creature.MovementType
 */
export enum Creature_MovementType {
  /**
   * @generated from enum value: MOVEMENT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MOVEMENT_TYPE_WALKING = 1;
   */
  WALKING = 1,

  /**
   * @generated from enum value: MOVEMENT_TYPE_SWIMMING = 2;
   */
  SWIMMING = 2,

  /**
   * @generated from enum value: MOVEMENT_TYPE_FLYING = 3;
   */
  FLYING = 3,

  /**
   * @generated from enum value: MOVEMENT_TYPE_PORTALING = 4;
   */
  PORTALING = 4,
}

/**
 * Describes the enum creature.v1.Creature.MovementType.
 */
export declare const Creature_MovementTypeSchema: GenEnum<Creature_MovementType>;

