// @generated by protoc-gen-es v2.6.3
// @generated from file creature/v1/creature.proto (package creature.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file creature/v1/creature.proto.
 */
export const file_creature_v1_creature = /*@__PURE__*/
  fileDesc("ChpjcmVhdHVyZS92MS9jcmVhdHVyZS5wcm90bxILY3JlYXR1cmUudjEi9wMKCENyZWF0dXJlGmgKFUF0dHJpYnV0ZU1vZGlmaWNhdGlvbhINCgVkZWx0YRgBIAEoBRIfChduZWdhdGVfcG9zaXRpdmVfZWZmZWN0cxgCIAEoCBIfChduZWdhdGVfbmVnYXRpdmVfZWZmZWN0cxgDIAEoCBriAQoES2luZBIKCgJpZBgBIAEoCRIMCgR0YWdzGAIgAygJEjoKDm1vdmVtZW50X3R5cGVzGAMgAygOMiIuY3JlYXR1cmUudjEuQ3JlYXR1cmUuTW92ZW1lbnRUeXBlEhcKD25hdGl2ZV90ZXJyYWlucxgEIAMoCRprCgZGaWx0ZXISCwoDYWxsGAEgASgIEhMKC2luY2x1ZGVfaWRzGAIgAygJEhMKC2V4Y2x1ZGVfaWRzGAMgAygJEhQKDGluY2x1ZGVfdGFncxgEIAMoCRIUCgxleGNsdWRlX3RhZ3MYBSADKAkimwEKDE1vdmVtZW50VHlwZRIdChlNT1ZFTUVOVF9UWVBFX1VOU1BFQ0lGSUVEEAASGQoVTU9WRU1FTlRfVFlQRV9XQUxLSU5HEAESGgoWTU9WRU1FTlRfVFlQRV9TV0lNTUlORxACEhgKFE1PVkVNRU5UX1RZUEVfRkxZSU5HEAMSGwoXTU9WRU1FTlRfVFlQRV9QT1JUQUxJTkcQBEKgAQoPY29tLmNyZWF0dXJlLnYxQg1DcmVhdHVyZVByb3RvUAFaMWdpdGh1Yi5jb20vb3BlbmhleGVzL3Byb3RvL2NyZWF0dXJlL3YxO2NyZWF0dXJldjGiAgNDWFiqAgtDcmVhdHVyZS5WMcoCC0NyZWF0dXJlXFYx4gIXQ3JlYXR1cmVcVjFcR1BCTWV0YWRhdGHqAgxDcmVhdHVyZTo6VjFiBnByb3RvMw");

/**
 * Describes the message creature.v1.Creature.
 * Use `create(CreatureSchema)` to create a new message.
 */
export const CreatureSchema = /*@__PURE__*/
  messageDesc(file_creature_v1_creature, 0);

/**
 * Describes the message creature.v1.Creature.AttributeModification.
 * Use `create(Creature_AttributeModificationSchema)` to create a new message.
 */
export const Creature_AttributeModificationSchema = /*@__PURE__*/
  messageDesc(file_creature_v1_creature, 0, 0);

/**
 * Describes the message creature.v1.Creature.Kind.
 * Use `create(Creature_KindSchema)` to create a new message.
 */
export const Creature_KindSchema = /*@__PURE__*/
  messageDesc(file_creature_v1_creature, 0, 1);

/**
 * Describes the message creature.v1.Creature.Kind.Filter.
 * Use `create(Creature_Kind_FilterSchema)` to create a new message.
 */
export const Creature_Kind_FilterSchema = /*@__PURE__*/
  messageDesc(file_creature_v1_creature, 0, 1, 0);

/**
 * Describes the enum creature.v1.Creature.MovementType.
 */
export const Creature_MovementTypeSchema = /*@__PURE__*/
  enumDesc(file_creature_v1_creature, 0, 0);

/**
 * @generated from enum creature.v1.Creature.MovementType
 */
export const Creature_MovementType = /*@__PURE__*/
  tsEnum(Creature_MovementTypeSchema);

