// @generated by protoc-gen-es v2.6.3
// @generated from file creature/v1/creature.proto (package creature.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file creature/v1/creature.proto.
 */
export const file_creature_v1_creature = /*@__PURE__*/
  fileDesc("ChpjcmVhdHVyZS92MS9jcmVhdHVyZS5wcm90bxILY3JlYXR1cmUudjEiygQKCENyZWF0dXJlGmgKFUF0dHJpYnV0ZU1vZGlmaWNhdGlvbhINCgVkZWx0YRgBIAEoBRIfChduZWdhdGVfcG9zaXRpdmVfZWZmZWN0cxgCIAEoCBIfChduZWdhdGVfbmVnYXRpdmVfZWZmZWN0cxgDIAEoCBq1AgoES2luZBIKCgJpZBgBIAEoCRIyCgR0YWdzGAIgAygLMiQuY3JlYXR1cmUudjEuQ3JlYXR1cmUuS2luZC5UYWdzRW50cnkSOgoObW92ZW1lbnRfdHlwZXMYAyADKA4yIi5jcmVhdHVyZS52MS5DcmVhdHVyZS5Nb3ZlbWVudFR5cGUSFwoPbmF0aXZlX3RlcnJhaW5zGAQgAygJGmsKBkZpbHRlchILCgNhbGwYASABKAgSEwoLaW5jbHVkZV9pZHMYAiADKAkSEwoLZXhjbHVkZV9pZHMYAyADKAkSFAoMaW5jbHVkZV90YWdzGAQgAygJEhQKDGV4Y2x1ZGVfdGFncxgFIAMoCRorCglUYWdzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgIOgI4ASKbAQoMTW92ZW1lbnRUeXBlEh0KGU1PVkVNRU5UX1RZUEVfVU5TUEVDSUZJRUQQABIZChVNT1ZFTUVOVF9UWVBFX1dBTEtJTkcQARIaChZNT1ZFTUVOVF9UWVBFX1NXSU1NSU5HEAISGAoUTU9WRU1FTlRfVFlQRV9GTFlJTkcQAxIbChdNT1ZFTUVOVF9UWVBFX1BPUlRBTElORxAEQqABCg9jb20uY3JlYXR1cmUudjFCDUNyZWF0dXJlUHJvdG9QAVoxZ2l0aHViLmNvbS9vcGVuaGV4ZXMvcHJvdG8vY3JlYXR1cmUvdjE7Y3JlYXR1cmV2MaICA0NYWKoCC0NyZWF0dXJlLlYxygILQ3JlYXR1cmVcVjHiAhdDcmVhdHVyZVxWMVxHUEJNZXRhZGF0YeoCDENyZWF0dXJlOjpWMWIGcHJvdG8z");

/**
 * Describes the message creature.v1.Creature.
 * Use `create(CreatureSchema)` to create a new message.
 */
export const CreatureSchema = /*@__PURE__*/
  messageDesc(file_creature_v1_creature, 0);

/**
 * Describes the message creature.v1.Creature.AttributeModification.
 * Use `create(Creature_AttributeModificationSchema)` to create a new message.
 */
export const Creature_AttributeModificationSchema = /*@__PURE__*/
  messageDesc(file_creature_v1_creature, 0, 0);

/**
 * Describes the message creature.v1.Creature.Kind.
 * Use `create(Creature_KindSchema)` to create a new message.
 */
export const Creature_KindSchema = /*@__PURE__*/
  messageDesc(file_creature_v1_creature, 0, 1);

/**
 * Describes the message creature.v1.Creature.Kind.Filter.
 * Use `create(Creature_Kind_FilterSchema)` to create a new message.
 */
export const Creature_Kind_FilterSchema = /*@__PURE__*/
  messageDesc(file_creature_v1_creature, 0, 1, 0);

/**
 * Describes the enum creature.v1.Creature.MovementType.
 */
export const Creature_MovementTypeSchema = /*@__PURE__*/
  enumDesc(file_creature_v1_creature, 0, 0);

/**
 * @generated from enum creature.v1.Creature.MovementType
 */
export const Creature_MovementType = /*@__PURE__*/
  tsEnum(Creature_MovementTypeSchema);

