// @generated by protoc-gen-es v2.6.3
// @generated from file map/v1/compass.proto (package map.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file map/v1/compass.proto.
 */
export const file_map_v1_compass = /*@__PURE__*/
  fileDesc("ChRtYXAvdjEvY29tcGFzcy5wcm90bxIGbWFwLnYxKpABCglEaXJlY3Rpb24SGQoVRElSRUNUSU9OX1VOU1BFQ0lGSUVEEAASDwoLRElSRUNUSU9OX1cQARIQCgxESVJFQ1RJT05fTlcQAhIQCgxESVJFQ1RJT05fTkUQBBIPCgtESVJFQ1RJT05fRRAFEhAKDERJUkVDVElPTl9TRRAGEhAKDERJUkVDVElPTl9TVxAHQnwKCmNvbS5tYXAudjFCDENvbXBhc3NQcm90b1ABWidnaXRodWIuY29tL29wZW5oZXhlcy9wcm90by9tYXAvdjE7bWFwdjGiAgNNWFiqAgZNYXAuVjHKAgZNYXBcVjHiAhJNYXBcVjFcR1BCTWV0YWRhdGHqAgdNYXA6OlYxYgZwcm90bzM");

/**
 * Describes the enum map.v1.Direction.
 */
export const DirectionSchema = /*@__PURE__*/
  enumDesc(file_map_v1_compass, 0);

/**
 * @generated from enum map.v1.Direction
 */
export const Direction = /*@__PURE__*/
  tsEnum(DirectionSchema);

