// @generated by protoc-gen-es v2.6.3
// @generated from file map/v1/compass.proto (package map.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file map/v1/compass.proto.
 */
export declare const file_map_v1_compass: GenFile;

/**
 * @generated from enum map.v1.Direction
 */
export enum Direction {
  /**
   * @generated from enum value: DIRECTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DIRECTION_W = 1;
   */
  W = 1,

  /**
   * @generated from enum value: DIRECTION_NW = 2;
   */
  NW = 2,

  /**
   * @generated from enum value: DIRECTION_NE = 4;
   */
  NE = 4,

  /**
   * @generated from enum value: DIRECTION_E = 5;
   */
  E = 5,

  /**
   * @generated from enum value: DIRECTION_SE = 6;
   */
  SE = 6,

  /**
   * @generated from enum value: DIRECTION_SW = 7;
   */
  SW = 7,
}

/**
 * Describes the enum map.v1.Direction.
 */
export declare const DirectionSchema: GenEnum<Direction>;

