// @generated by protoc-gen-es v2.6.3
// @generated from file map/v1/compass.proto (package map.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file map/v1/compass.proto.
 */
export declare const file_map_v1_compass: GenFile;

/**
 * @generated from enum map.v1.EdgeDirection
 */
export enum EdgeDirection {
  /**
   * @generated from enum value: EDGE_DIRECTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: EDGE_DIRECTION_W = 1;
   */
  W = 1,

  /**
   * @generated from enum value: EDGE_DIRECTION_NW = 2;
   */
  NW = 2,

  /**
   * @generated from enum value: EDGE_DIRECTION_NE = 4;
   */
  NE = 4,

  /**
   * @generated from enum value: EDGE_DIRECTION_E = 5;
   */
  E = 5,

  /**
   * @generated from enum value: EDGE_DIRECTION_SE = 6;
   */
  SE = 6,

  /**
   * @generated from enum value: EDGE_DIRECTION_SW = 7;
   */
  SW = 7,
}

/**
 * Describes the enum map.v1.EdgeDirection.
 */
export declare const EdgeDirectionSchema: GenEnum<EdgeDirection>;

/**
 * @generated from enum map.v1.CornerDirection
 */
export enum CornerDirection {
  /**
   * @generated from enum value: CORNER_DIRECTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CORNER_DIRECTION_NW = 1;
   */
  NW = 1,

  /**
   * @generated from enum value: CORNER_DIRECTION_N = 2;
   */
  N = 2,

  /**
   * @generated from enum value: CORNER_DIRECTION_NE = 3;
   */
  NE = 3,

  /**
   * @generated from enum value: CORNER_DIRECTION_SE = 4;
   */
  SE = 4,

  /**
   * @generated from enum value: CORNER_DIRECTION_S = 5;
   */
  S = 5,

  /**
   * @generated from enum value: CORNER_DIRECTION_SW = 6;
   */
  SW = 6,
}

/**
 * Describes the enum map.v1.CornerDirection.
 */
export declare const CornerDirectionSchema: GenEnum<CornerDirection>;

