// @generated by protoc-gen-es v2.6.3
// @generated from file map/v1/terrain.proto (package map.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Spell_Filter } from "../../magic/v1/spell_pb";
import type { Creature_AttributeModification, Creature_Kind_Filter, Creature_MovementType } from "../../creatures/v1/creature_pb";

/**
 * Describes the file map/v1/terrain.proto.
 */
export declare const file_map_v1_terrain: GenFile;

/**
 * @generated from message map.v1.Terrain
 */
export declare type Terrain = Message<"map.v1.Terrain"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: repeated string tags = 2;
   */
  tags: string[];

  /**
   * @generated from field: uint32 movement_penalty = 3;
   */
  movementPenalty: number;

  /**
   * @generated from field: repeated map.v1.Terrain.MovementType passable_with = 4;
   */
  passableWith: Terrain_MovementType[];

  /**
   * @generated from field: repeated map.v1.Terrain.Effect effects = 5;
   */
  effects: Terrain_Effect[];

  /**
   * @generated from field: map.v1.Terrain.RenderingSpec rendering_spec = 6;
   */
  renderingSpec?: Terrain_RenderingSpec;
};

/**
 * Describes the message map.v1.Terrain.
 * Use `create(TerrainSchema)` to create a new message.
 */
export declare const TerrainSchema: GenMessage<Terrain>;

/**
 * @generated from message map.v1.Terrain.Effect
 */
export declare type Terrain_Effect = Message<"map.v1.Terrain.Effect"> & {
  /**
   * @generated from oneof map.v1.Terrain.Effect.kind
   */
  kind: {
    /**
     * @generated from field: map.v1.Terrain.Effect.ModifySpellLevel modify_spell_level = 1;
     */
    value: Terrain_Effect_ModifySpellLevel;
    case: "modifySpellLevel";
  } | {
    /**
     * @generated from field: map.v1.Terrain.Effect.PreventSpellCasting prevent_spell_casting = 2;
     */
    value: Terrain_Effect_PreventSpellCasting;
    case: "preventSpellCasting";
  } | {
    /**
     * @generated from field: map.v1.Terrain.Effect.DisableNativeTerrainBonuses disable_native_terrain_bonuses = 3;
     */
    value: Terrain_Effect_DisableNativeTerrainBonuses;
    case: "disableNativeTerrainBonuses";
  } | {
    /**
     * @generated from field: map.v1.Terrain.Effect.ModifyCreatureMovementType modify_creature_movement_type = 4;
     */
    value: Terrain_Effect_ModifyCreatureMovementType;
    case: "modifyCreatureMovementType";
  } | {
    /**
     * @generated from field: map.v1.Terrain.Effect.ModifyCreatureMorale modify_creature_morale = 5;
     */
    value: Terrain_Effect_ModifyCreatureMorale;
    case: "modifyCreatureMorale";
  } | {
    /**
     * @generated from field: map.v1.Terrain.Effect.ModifyCreatureLuck modify_creature_luck = 6;
     */
    value: Terrain_Effect_ModifyCreatureLuck;
    case: "modifyCreatureLuck";
  } | {
    /**
     * @generated from field: map.v1.Terrain.Effect.ModifyCreatureAttack modify_creature_attack = 7;
     */
    value: Terrain_Effect_ModifyCreatureAttack;
    case: "modifyCreatureAttack";
  } | {
    /**
     * @generated from field: map.v1.Terrain.Effect.ModifyCreatureDefence modify_creature_defence = 8;
     */
    value: Terrain_Effect_ModifyCreatureDefence;
    case: "modifyCreatureDefence";
  } | {
    /**
     * @generated from field: map.v1.Terrain.Effect.ModifyCreatureSpeed modify_creature_speed = 9;
     */
    value: Terrain_Effect_ModifyCreatureSpeed;
    case: "modifyCreatureSpeed";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message map.v1.Terrain.Effect.
 * Use `create(Terrain_EffectSchema)` to create a new message.
 */
export declare const Terrain_EffectSchema: GenMessage<Terrain_Effect>;

/**
 * @generated from message map.v1.Terrain.Effect.ModifySpellLevel
 */
export declare type Terrain_Effect_ModifySpellLevel = Message<"map.v1.Terrain.Effect.ModifySpellLevel"> & {
  /**
   * @generated from field: magic.v1.Spell.Filter filter = 1;
   */
  filter?: Spell_Filter;

  /**
   * @generated from field: int32 delta = 2;
   */
  delta: number;
};

/**
 * Describes the message map.v1.Terrain.Effect.ModifySpellLevel.
 * Use `create(Terrain_Effect_ModifySpellLevelSchema)` to create a new message.
 */
export declare const Terrain_Effect_ModifySpellLevelSchema: GenMessage<Terrain_Effect_ModifySpellLevel>;

/**
 * @generated from message map.v1.Terrain.Effect.PreventSpellCasting
 */
export declare type Terrain_Effect_PreventSpellCasting = Message<"map.v1.Terrain.Effect.PreventSpellCasting"> & {
  /**
   * @generated from field: magic.v1.Spell.Filter filter = 1;
   */
  filter?: Spell_Filter;

  /**
   * @generated from field: optional int32 level_gte = 2;
   */
  levelGte?: number;

  /**
   * @generated from field: optional int32 level_lte = 3;
   */
  levelLte?: number;
};

/**
 * Describes the message map.v1.Terrain.Effect.PreventSpellCasting.
 * Use `create(Terrain_Effect_PreventSpellCastingSchema)` to create a new message.
 */
export declare const Terrain_Effect_PreventSpellCastingSchema: GenMessage<Terrain_Effect_PreventSpellCasting>;

/**
 * @generated from message map.v1.Terrain.Effect.DisableNativeTerrainBonuses
 */
export declare type Terrain_Effect_DisableNativeTerrainBonuses = Message<"map.v1.Terrain.Effect.DisableNativeTerrainBonuses"> & {
};

/**
 * Describes the message map.v1.Terrain.Effect.DisableNativeTerrainBonuses.
 * Use `create(Terrain_Effect_DisableNativeTerrainBonusesSchema)` to create a new message.
 */
export declare const Terrain_Effect_DisableNativeTerrainBonusesSchema: GenMessage<Terrain_Effect_DisableNativeTerrainBonuses>;

/**
 * @generated from message map.v1.Terrain.Effect.ModifyCreatureMovementType
 */
export declare type Terrain_Effect_ModifyCreatureMovementType = Message<"map.v1.Terrain.Effect.ModifyCreatureMovementType"> & {
  /**
   * @generated from field: creatures.v1.Creature.Kind.Filter filter = 1;
   */
  filter?: Creature_Kind_Filter;

  /**
   * @generated from field: repeated creatures.v1.Creature.MovementType remove = 2;
   */
  remove: Creature_MovementType[];

  /**
   * @generated from field: repeated creatures.v1.Creature.MovementType add = 3;
   */
  add: Creature_MovementType[];
};

/**
 * Describes the message map.v1.Terrain.Effect.ModifyCreatureMovementType.
 * Use `create(Terrain_Effect_ModifyCreatureMovementTypeSchema)` to create a new message.
 */
export declare const Terrain_Effect_ModifyCreatureMovementTypeSchema: GenMessage<Terrain_Effect_ModifyCreatureMovementType>;

/**
 * @generated from message map.v1.Terrain.Effect.ModifyCreatureMorale
 */
export declare type Terrain_Effect_ModifyCreatureMorale = Message<"map.v1.Terrain.Effect.ModifyCreatureMorale"> & {
  /**
   * @generated from field: creatures.v1.Creature.Kind.Filter filter = 1;
   */
  filter?: Creature_Kind_Filter;

  /**
   * @generated from field: creatures.v1.Creature.AttributeModification modification = 2;
   */
  modification?: Creature_AttributeModification;
};

/**
 * Describes the message map.v1.Terrain.Effect.ModifyCreatureMorale.
 * Use `create(Terrain_Effect_ModifyCreatureMoraleSchema)` to create a new message.
 */
export declare const Terrain_Effect_ModifyCreatureMoraleSchema: GenMessage<Terrain_Effect_ModifyCreatureMorale>;

/**
 * @generated from message map.v1.Terrain.Effect.ModifyCreatureLuck
 */
export declare type Terrain_Effect_ModifyCreatureLuck = Message<"map.v1.Terrain.Effect.ModifyCreatureLuck"> & {
  /**
   * @generated from field: creatures.v1.Creature.Kind.Filter filter = 1;
   */
  filter?: Creature_Kind_Filter;

  /**
   * @generated from field: creatures.v1.Creature.AttributeModification modification = 2;
   */
  modification?: Creature_AttributeModification;
};

/**
 * Describes the message map.v1.Terrain.Effect.ModifyCreatureLuck.
 * Use `create(Terrain_Effect_ModifyCreatureLuckSchema)` to create a new message.
 */
export declare const Terrain_Effect_ModifyCreatureLuckSchema: GenMessage<Terrain_Effect_ModifyCreatureLuck>;

/**
 * @generated from message map.v1.Terrain.Effect.ModifyCreatureAttack
 */
export declare type Terrain_Effect_ModifyCreatureAttack = Message<"map.v1.Terrain.Effect.ModifyCreatureAttack"> & {
  /**
   * @generated from field: creatures.v1.Creature.Kind.Filter filter = 1;
   */
  filter?: Creature_Kind_Filter;

  /**
   * @generated from field: creatures.v1.Creature.AttributeModification modification = 2;
   */
  modification?: Creature_AttributeModification;
};

/**
 * Describes the message map.v1.Terrain.Effect.ModifyCreatureAttack.
 * Use `create(Terrain_Effect_ModifyCreatureAttackSchema)` to create a new message.
 */
export declare const Terrain_Effect_ModifyCreatureAttackSchema: GenMessage<Terrain_Effect_ModifyCreatureAttack>;

/**
 * @generated from message map.v1.Terrain.Effect.ModifyCreatureDefence
 */
export declare type Terrain_Effect_ModifyCreatureDefence = Message<"map.v1.Terrain.Effect.ModifyCreatureDefence"> & {
  /**
   * @generated from field: creatures.v1.Creature.Kind.Filter filter = 1;
   */
  filter?: Creature_Kind_Filter;

  /**
   * @generated from field: creatures.v1.Creature.AttributeModification modification = 2;
   */
  modification?: Creature_AttributeModification;
};

/**
 * Describes the message map.v1.Terrain.Effect.ModifyCreatureDefence.
 * Use `create(Terrain_Effect_ModifyCreatureDefenceSchema)` to create a new message.
 */
export declare const Terrain_Effect_ModifyCreatureDefenceSchema: GenMessage<Terrain_Effect_ModifyCreatureDefence>;

/**
 * @generated from message map.v1.Terrain.Effect.ModifyCreatureSpeed
 */
export declare type Terrain_Effect_ModifyCreatureSpeed = Message<"map.v1.Terrain.Effect.ModifyCreatureSpeed"> & {
  /**
   * @generated from field: creatures.v1.Creature.Kind.Filter filter = 1;
   */
  filter?: Creature_Kind_Filter;

  /**
   * @generated from field: creatures.v1.Creature.AttributeModification modification = 2;
   */
  modification?: Creature_AttributeModification;
};

/**
 * Describes the message map.v1.Terrain.Effect.ModifyCreatureSpeed.
 * Use `create(Terrain_Effect_ModifyCreatureSpeedSchema)` to create a new message.
 */
export declare const Terrain_Effect_ModifyCreatureSpeedSchema: GenMessage<Terrain_Effect_ModifyCreatureSpeed>;

/**
 * @generated from message map.v1.Terrain.RenderingSpec
 */
export declare type Terrain_RenderingSpec = Message<"map.v1.Terrain.RenderingSpec"> & {
  /**
   * @generated from field: string color = 1;
   */
  color: string;

  /**
   * @generated from field: string texture = 2;
   */
  texture: string;
};

/**
 * Describes the message map.v1.Terrain.RenderingSpec.
 * Use `create(Terrain_RenderingSpecSchema)` to create a new message.
 */
export declare const Terrain_RenderingSpecSchema: GenMessage<Terrain_RenderingSpec>;

/**
 * @generated from enum map.v1.Terrain.MovementType
 */
export enum Terrain_MovementType {
  /**
   * @generated from enum value: MOVEMENT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MOVEMENT_TYPE_WALKING = 1;
   */
  WALKING = 1,

  /**
   * @generated from enum value: MOVEMENT_TYPE_SWIMMING = 2;
   */
  SWIMMING = 2,

  /**
   * @generated from enum value: MOVEMENT_TYPE_FLYING = 3;
   */
  FLYING = 3,

  /**
   * @generated from enum value: MOVEMENT_TYPE_PORTALING = 4;
   */
  PORTALING = 4,
}

/**
 * Describes the enum map.v1.Terrain.MovementType.
 */
export declare const Terrain_MovementTypeSchema: GenEnum<Terrain_MovementType>;

