// @generated by protoc-gen-es v2.6.3
// @generated from file map/v1/tile.proto (package map.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Terrain } from "./terrain_pb";

/**
 * Describes the file map/v1/tile.proto.
 */
export declare const file_map_v1_tile: GenFile;

/**
 * @generated from message map.v1.Tile
 */
export declare type Tile = Message<"map.v1.Tile"> & {
  /**
   * @generated from field: map.v1.Tile.Coordinate coordinate = 1;
   */
  coordinate?: Tile_Coordinate;

  /**
   * @generated from field: map.v1.Terrain terrain = 2;
   */
  terrain?: Terrain;
};

/**
 * Describes the message map.v1.Tile.
 * Use `create(TileSchema)` to create a new message.
 */
export declare const TileSchema: GenMessage<Tile>;

/**
 * @generated from message map.v1.Tile.Coordinate
 */
export declare type Tile_Coordinate = Message<"map.v1.Tile.Coordinate"> & {
  /**
   * @generated from field: uint32 row = 1;
   */
  row: number;

  /**
   * @generated from field: uint32 column = 2;
   */
  column: number;

  /**
   * @generated from field: uint32 depth = 3;
   */
  depth: number;
};

/**
 * Describes the message map.v1.Tile.Coordinate.
 * Use `create(Tile_CoordinateSchema)` to create a new message.
 */
export declare const Tile_CoordinateSchema: GenMessage<Tile_Coordinate>;

