// @generated by protoc-gen-es v2.6.3
// @generated from file map/v1/tile.proto (package map.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_map_v1_compass } from "./compass_pb";

/**
 * Describes the file map/v1/tile.proto.
 */
export const file_map_v1_tile = /*@__PURE__*/
  fileDesc("ChFtYXAvdjEvdGlsZS5wcm90bxIGbWFwLnYxIsgDCgRUaWxlEisKCmNvb3JkaW5hdGUYASABKAsyFy5tYXAudjEuVGlsZS5Db29yZGluYXRlEhIKCnRlcnJhaW5faWQYAiABKAkSMgoOcmVuZGVyaW5nX3NwZWMYAyABKAsyGi5tYXAudjEuVGlsZS5SZW5kZXJpbmdTcGVjGjgKCkNvb3JkaW5hdGUSCwoDcm93GAEgASgNEg4KBmNvbHVtbhgCIAEoDRINCgVkZXB0aBgDIAEoDRpOCgRFZGdlEigKCWRpcmVjdGlvbhgBIAEoDjIVLm1hcC52MS5FZGdlRGlyZWN0aW9uEhwKFG5laWdoYm91cl90ZXJyYWluX2lkGAIgASgJGlMKBkNvcm5lchIqCglkaXJlY3Rpb24YASABKA4yFy5tYXAudjEuQ29ybmVyRGlyZWN0aW9uEh0KFW5laWdoYm91cl90ZXJyYWluX2lkcxgCIAMoCRpsCg1SZW5kZXJpbmdTcGVjEiAKBWVkZ2VzGAEgAygLMhEubWFwLnYxLlRpbGUuRWRnZRIkCgdjb3JuZXJzGAIgAygLMhMubWFwLnYxLlRpbGUuQ29ybmVyEhMKC2ZlYXR1cmVfaWRzGAMgAygJIqECCgdTZWdtZW50EiYKBmJvdW5kcxgBIAEoCzIWLm1hcC52MS5TZWdtZW50LkJvdW5kcxIbCgV0aWxlcxgCIAMoCzIMLm1hcC52MS5UaWxlEjUKDnJlbmRlcmluZ19zcGVjGAMgASgLMh0ubWFwLnYxLlNlZ21lbnQuUmVuZGVyaW5nU3BlYxpSCgZCb3VuZHMSDwoHbWluX3JvdxgBIAEoBRIPCgdtYXhfcm93GAIgASgFEhIKCm1pbl9jb2x1bW4YAyABKAUSEgoKbWF4X2NvbHVtbhgEIAEoBRocCg1SZW5kZXJpbmdTcGVjEgsKA3N2ZxgBIAEoCRooCgNSb3cSIQoIc2VnbWVudHMYASADKAsyDy5tYXAudjEuU2VnbWVudCJrCgRHcmlkEikKDHNlZ21lbnRfcm93cxgBIAMoCzITLm1hcC52MS5TZWdtZW50LlJvdxISCgp0b3RhbF9yb3dzGAIgASgNEhUKDXRvdGFsX2NvbHVtbnMYAyABKA0SDQoFZGVwdGgYBCABKA1CeQoKY29tLm1hcC52MUIJVGlsZVByb3RvUAFaJ2dpdGh1Yi5jb20vb3BlbmhleGVzL3Byb3RvL21hcC92MTttYXB2MaICA01YWKoCBk1hcC5WMcoCBk1hcFxWMeICEk1hcFxWMVxHUEJNZXRhZGF0YeoCB01hcDo6VjFiBnByb3RvMw", [file_map_v1_compass]);

/**
 * Describes the message map.v1.Tile.
 * Use `create(TileSchema)` to create a new message.
 */
export const TileSchema = /*@__PURE__*/
  messageDesc(file_map_v1_tile, 0);

/**
 * Describes the message map.v1.Tile.Coordinate.
 * Use `create(Tile_CoordinateSchema)` to create a new message.
 */
export const Tile_CoordinateSchema = /*@__PURE__*/
  messageDesc(file_map_v1_tile, 0, 0);

/**
 * Describes the message map.v1.Tile.Edge.
 * Use `create(Tile_EdgeSchema)` to create a new message.
 */
export const Tile_EdgeSchema = /*@__PURE__*/
  messageDesc(file_map_v1_tile, 0, 1);

/**
 * Describes the message map.v1.Tile.Corner.
 * Use `create(Tile_CornerSchema)` to create a new message.
 */
export const Tile_CornerSchema = /*@__PURE__*/
  messageDesc(file_map_v1_tile, 0, 2);

/**
 * Describes the message map.v1.Tile.RenderingSpec.
 * Use `create(Tile_RenderingSpecSchema)` to create a new message.
 */
export const Tile_RenderingSpecSchema = /*@__PURE__*/
  messageDesc(file_map_v1_tile, 0, 3);

/**
 * Describes the message map.v1.Segment.
 * Use `create(SegmentSchema)` to create a new message.
 */
export const SegmentSchema = /*@__PURE__*/
  messageDesc(file_map_v1_tile, 1);

/**
 * Describes the message map.v1.Segment.Bounds.
 * Use `create(Segment_BoundsSchema)` to create a new message.
 */
export const Segment_BoundsSchema = /*@__PURE__*/
  messageDesc(file_map_v1_tile, 1, 0);

/**
 * Describes the message map.v1.Segment.RenderingSpec.
 * Use `create(Segment_RenderingSpecSchema)` to create a new message.
 */
export const Segment_RenderingSpecSchema = /*@__PURE__*/
  messageDesc(file_map_v1_tile, 1, 1);

/**
 * Describes the message map.v1.Segment.Row.
 * Use `create(Segment_RowSchema)` to create a new message.
 */
export const Segment_RowSchema = /*@__PURE__*/
  messageDesc(file_map_v1_tile, 1, 2);

/**
 * Describes the message map.v1.Grid.
 * Use `create(GridSchema)` to create a new message.
 */
export const GridSchema = /*@__PURE__*/
  messageDesc(file_map_v1_tile, 2);

