// @generated by protoc-gen-es v2.6.3
// @generated from file map/v1/tile.proto (package map.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file map/v1/tile.proto.
 */
export const file_map_v1_tile = /*@__PURE__*/
  fileDesc("ChFtYXAvdjEvdGlsZS5wcm90bxIGbWFwLnYxIoEBCgRUaWxlEisKCmNvb3JkaW5hdGUYASABKAsyFy5tYXAudjEuVGlsZS5Db29yZGluYXRlEhIKCnRlcnJhaW5faWQYAiABKAkaOAoKQ29vcmRpbmF0ZRILCgNyb3cYASABKA0SDgoGY29sdW1uGAIgASgNEg0KBWRlcHRoGAMgASgNQnkKCmNvbS5tYXAudjFCCVRpbGVQcm90b1ABWidnaXRodWIuY29tL29wZW5oZXhlcy9wcm90by9tYXAvdjE7bWFwdjGiAgNNWFiqAgZNYXAuVjHKAgZNYXBcVjHiAhJNYXBcVjFcR1BCTWV0YWRhdGHqAgdNYXA6OlYxYgZwcm90bzM");

/**
 * Describes the message map.v1.Tile.
 * Use `create(TileSchema)` to create a new message.
 */
export const TileSchema = /*@__PURE__*/
  messageDesc(file_map_v1_tile, 0);

/**
 * Describes the message map.v1.Tile.Coordinate.
 * Use `create(Tile_CoordinateSchema)` to create a new message.
 */
export const Tile_CoordinateSchema = /*@__PURE__*/
  messageDesc(file_map_v1_tile, 0, 0);

