// @generated by protoc-gen-es v2.6.3
// @generated from file map/v1/tile.proto (package map.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_map_v1_compass } from "./compass_pb";

/**
 * Describes the file map/v1/tile.proto.
 */
export const file_map_v1_tile = /*@__PURE__*/
  fileDesc("ChFtYXAvdjEvdGlsZS5wcm90bxIGbWFwLnYxIskCCgRUaWxlEisKCmNvb3JkaW5hdGUYASABKAsyFy5tYXAudjEuVGlsZS5Db29yZGluYXRlEhIKCnRlcnJhaW5faWQYAiABKAkSMgoOcmVuZGVyaW5nX3NwZWMYAyABKAsyGi5tYXAudjEuVGlsZS5SZW5kZXJpbmdTcGVjGjgKCkNvb3JkaW5hdGUSCwoDcm93GAEgASgNEg4KBmNvbHVtbhgCIAEoDRINCgVkZXB0aBgDIAEoDRpKCgRFZGdlEiQKCWRpcmVjdGlvbhgBIAEoDjIRLm1hcC52MS5EaXJlY3Rpb24SHAoUbmVpZ2hib3VyX3RlcnJhaW5faWQYAiABKAkaRgoNUmVuZGVyaW5nU3BlYxIgCgVlZGdlcxgBIAMoCzIRLm1hcC52MS5UaWxlLkVkZ2USEwoLZmVhdHVyZV9pZHMYAiADKAkizAEKB1NlZ21lbnQSJgoGYm91bmRzGAEgASgLMhYubWFwLnYxLlNlZ21lbnQuQm91bmRzEhsKBXRpbGVzGAIgAygLMgwubWFwLnYxLlRpbGUaUgoGQm91bmRzEg8KB21pbl9yb3cYASABKAUSDwoHbWF4X3JvdxgCIAEoBRISCgptaW5fY29sdW1uGAMgASgFEhIKCm1heF9jb2x1bW4YBCABKAUaKAoDUm93EiEKCHNlZ21lbnRzGAEgAygLMg8ubWFwLnYxLlNlZ21lbnQiXAoER3JpZBIpCgxzZWdtZW50X3Jvd3MYASADKAsyEy5tYXAudjEuU2VnbWVudC5Sb3cSEgoKdG90YWxfcm93cxgCIAEoDRIVCg10b3RhbF9jb2x1bW5zGAMgASgNQnkKCmNvbS5tYXAudjFCCVRpbGVQcm90b1ABWidnaXRodWIuY29tL29wZW5oZXhlcy9wcm90by9tYXAvdjE7bWFwdjGiAgNNWFiqAgZNYXAuVjHKAgZNYXBcVjHiAhJNYXBcVjFcR1BCTWV0YWRhdGHqAgdNYXA6OlYxYgZwcm90bzM", [file_map_v1_compass]);

/**
 * Describes the message map.v1.Tile.
 * Use `create(TileSchema)` to create a new message.
 */
export const TileSchema = /*@__PURE__*/
  messageDesc(file_map_v1_tile, 0);

/**
 * Describes the message map.v1.Tile.Coordinate.
 * Use `create(Tile_CoordinateSchema)` to create a new message.
 */
export const Tile_CoordinateSchema = /*@__PURE__*/
  messageDesc(file_map_v1_tile, 0, 0);

/**
 * Describes the message map.v1.Tile.Edge.
 * Use `create(Tile_EdgeSchema)` to create a new message.
 */
export const Tile_EdgeSchema = /*@__PURE__*/
  messageDesc(file_map_v1_tile, 0, 1);

/**
 * Describes the message map.v1.Tile.RenderingSpec.
 * Use `create(Tile_RenderingSpecSchema)` to create a new message.
 */
export const Tile_RenderingSpecSchema = /*@__PURE__*/
  messageDesc(file_map_v1_tile, 0, 2);

/**
 * Describes the message map.v1.Segment.
 * Use `create(SegmentSchema)` to create a new message.
 */
export const SegmentSchema = /*@__PURE__*/
  messageDesc(file_map_v1_tile, 1);

/**
 * Describes the message map.v1.Segment.Bounds.
 * Use `create(Segment_BoundsSchema)` to create a new message.
 */
export const Segment_BoundsSchema = /*@__PURE__*/
  messageDesc(file_map_v1_tile, 1, 0);

/**
 * Describes the message map.v1.Segment.Row.
 * Use `create(Segment_RowSchema)` to create a new message.
 */
export const Segment_RowSchema = /*@__PURE__*/
  messageDesc(file_map_v1_tile, 1, 1);

/**
 * Describes the message map.v1.Grid.
 * Use `create(GridSchema)` to create a new message.
 */
export const GridSchema = /*@__PURE__*/
  messageDesc(file_map_v1_tile, 2);

